import { Platform, StyleSheet } from "react-native";
import Theme from "@pulse/core/constants/Theme";
import Layout from "@pulse/core/constants/Layout";
import { withWebSafeShadows } from "@pulse/core/lib/platformViewStyle.util";

const DETAIL_REF = {
  pageBg: "#ffffff",
  headerTitle: "#18181b",
} as const;

export const tripHistoryDetailStyles = withWebSafeShadows(
  StyleSheet.create({
  detailWrap: {
    flex: 1,
    // Allow ScrollView to shrink below content height so it can scroll
    // (html/body/#root use overflow:hidden on web — see lib/htmlShell.ts).
    minHeight: 0,
    width: "100%",
    backgroundColor: DETAIL_REF.pageBg,
  },
  detailLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  detailHeaderRef: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    gap: 10,
    flexShrink: 0,
  },
  detailHeaderStyled: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  detailBack: {
    minWidth: 36,
    minHeight: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  detailBackStyled: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
  },
  detailHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  detailTitleWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    minWidth: 0,
    marginLeft: 12,
  },
  tdHeaderCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 0,
  },
  tdStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
      },
      default: { elevation: 2 },
    }),
  },
  tdHeroOuter: {
    marginBottom: 20,
    borderRadius: 40,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.2,
        shadowRadius: 24,
      },
      default: { elevation: 10 },
    }),
  },
  tdHeroCard: {
    borderRadius: 40,
    padding: 32,
    paddingBottom: 28,
    overflow: "hidden",
  },
  tdHeroGlow: {
    position: "absolute",
    bottom: -48,
    left: -48,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(16,185,129,0.22)",
    opacity: 1,
  },
  tdHeroWatermark: {
    position: "absolute",
    top: 28,
    right: 28,
    opacity: 1,
    transform: [{ rotate: "12deg" }],
  },
  tdHeroInner: {
    position: "relative",
    zIndex: 2,
  },
  tdHeroKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 4,
    color: "rgba(148,163,184,0.95)",
    textTransform: "uppercase",
    marginBottom: 24,
  },
  tdHeroRouteRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 22,
  },
  tdHeroRouteSide: {
    flex: 1,
    minWidth: 0,
  },
  tdHeroRouteSideRight: {
    alignItems: "flex-end",
  },
  tdHeroCity: {
    fontSize: 24,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: -1,
    textTransform: "uppercase",
    lineHeight: 27,
  },
  tdHeroCityRight: {
    textAlign: "right",
  },
  tdHeroState: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2.8,
    color: "rgba(148,163,184,0.95)",
    textTransform: "uppercase",
    marginTop: 7,
    maxWidth: "100%",
  },
  tdHeroStateRight: {
    textAlign: "right",
  },
  tdHeroRouteConnector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    width: 48,
    paddingTop: 12,
  },
  tdHeroToRail: {
    alignItems: "center",
    width: 14,
  },
  tdHeroDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  tdHeroRailGrad: {
    width: 2,
    height: 18,
    marginTop: 2,
    borderRadius: 1,
  },
  tdHeroConnectorLine: {
    flex: 1,
    height: 1,
    minWidth: 6,
    backgroundColor: "rgba(148,163,184,0.3)",
  },
  tdHeroToLabel: {
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  tdHeroDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255,255,255,0.12)",
    marginBottom: 18,
  },
  tdHeroMetaRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 28,
  },
  tdHeroMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  tdHeroMetaIconWrap: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  tdHeroMetaKicker: {
    fontSize: 9,
    fontWeight: "800",
    color: "rgba(148,163,184,0.95)",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  tdHeroMetaValue: {
    fontSize: 13,
    fontWeight: "800",
    color: "#ffffff",
    letterSpacing: 0.5,
  },
  tdHeroAssignerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.16)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tdHeroAssignerLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "rgba(148,163,184,0.95)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  tdHeroAssignerValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "800",
    color: "#ffffff",
  },
  tdHeroAccentBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 4,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  tdTabBar: {
    flexDirection: "row",
    padding: 4,
    borderRadius: 12,
    gap: 4,
    marginBottom: 12,
  },
  tdTabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    minHeight: 40,
  },
  tdTabBtnActive: {
    backgroundColor: "#0f172a",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      default: { elevation: 4 },
    }),
  },
  tdTabLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    lineHeight: 13,
  },
  tdTimelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  tdTimelineHeaderIcon: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  tdTimelineHeaderTitle: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    lineHeight: 12,
    flex: 1,
    minWidth: 0,
  },
  tdTimelineCard: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
    overflow: "visible",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      default: { elevation: 2 },
    }),
  },
  tdEmptyTimeline: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    paddingVertical: 14,
    lineHeight: 15,
  },
  tdPodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    minHeight: 44,
  },
  tdPodFileName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 18,
  },
  tdPodPreview: {
    fontSize: 12,
    fontWeight: "500",
  },
  tdLogRowWrap: {
    position: "relative",
    paddingBottom: 12,
  },
  tdLogConnector: {
    position: "absolute",
    left: 22,
    top: 30,
    bottom: 0,
    width: 2,
    zIndex: 0,
  },
  tdLogTouchable: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingLeft: 4,
    paddingRight: 4,
    paddingVertical: 6,
    zIndex: 1,
  },
  tdLogMarkerCol: {
    width: 32,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 1,
    flexShrink: 0,
  },
  tdLogCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    ...Platform.select({
      ios: {
        shadowColor: Theme.driverEmerald,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      default: { elevation: 2 },
    }),
  },
  tdLogBody: {
    flex: 1,
    minWidth: 0,
  },
  tdLogHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    marginBottom: 2,
    minHeight: 22,
  },
  tdLogHeadRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  tdLogStatus: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.1,
    flexShrink: 1,
    lineHeight: 16,
  },
  tdLogTime: {
    fontSize: 9,
    fontWeight: "700",
    lineHeight: 12,
  },
  tdLogLoc: {
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
  },
  tdLogExpanded: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(148,163,184,0.35)",
  },
  tdLogFactCard: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
    gap: 10,
  },
  tdLogDriverLocRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  tdLogDriverLocIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 1,
  },
  tdLogDriverLocCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  tdLogFactDivider: {
    height: StyleSheet.hairlineWidth,
  },
  tdLogFactGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  tdLogFactCol: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  tdLogFactRule: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    marginHorizontal: 12,
  },
  tdLogFactLabel: {
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  tdLogFactValue: {
    fontSize: 13,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 18,
  },
  tdLogDocRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: -2,
    marginBottom: 4,
  },
  tdLogDocThumb: {
    width: 56,
    height: 56,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  tdLogDocImage: {
    width: "100%",
    height: "100%",
  },
  tdLogDetailsKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  tdLogDetailsBox: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
    marginBottom: 10,
  },
  tdLogDetailsText: {
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 17,
  },
  tdLogMetaGrid: {
    flexDirection: "row",
    gap: 24,
    flexWrap: "wrap",
  },
  tdLogMetaK: {
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  tdLogMetaV: {
    fontSize: 11,
    fontWeight: "600",
  },
  tdLogInTransitGrid: {
    flexDirection: "row",
    gap: 16,
    alignItems: "flex-start",
  },
  tdLogInTransitCol: {
    flex: 1,
    minWidth: 0,
  },
  tdDeliveredBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginTop: 4,
  },
  tdDeliveredKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 3,
    color: "rgba(236,253,245,0.95)",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  tdDeliveredTitle: {
    fontSize: 14,
    fontWeight: "800",
    fontStyle: "italic",
    color: "#ffffff",
    letterSpacing: -0.2,
    lineHeight: 18,
  },
  tdDeliveredIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  tdProgressBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginTop: 4,
    borderWidth: 1,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      default: { elevation: 2 },
    }),
  },
  tdProgressKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  tdProgressTitle: {
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
    fontStyle: "italic",
    lineHeight: 18,
  },
  tdSettlementGlow: {
    marginBottom: 12,
    borderRadius: 16,
    padding: 2,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  tdNetCard: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      default: { elevation: 2 },
    }),
  },
  tdNetBlur: {
    position: "absolute",
    top: -32,
    right: -32,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(16,185,129,0.14)",
    opacity: 1,
  },
  tdNetHeader: {
    alignItems: "center",
  },
  tdNetWalletIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: "rgba(16,185,129,0.12)",
  },
  tdNetKicker: {
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 2,
    marginBottom: 6,
    textTransform: "uppercase",
    lineHeight: 11,
  },
  tdNetAmountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 2,
    marginBottom: 8,
    maxWidth: "100%",
  },
  tdNetRupee: {
    fontSize: 16,
    fontWeight: "700",
    marginRight: 1,
    lineHeight: 22,
  },
  tdNetAmount: {
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -1,
    flexShrink: 1,
    lineHeight: 30,
  },
  tdNetSuccessPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  tdNetSuccessText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    lineHeight: 12,
  },
  tdNetMiniGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  tdNetMiniCard: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    minWidth: 0,
  },
  tdNetMiniK: {
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 4,
    textTransform: "uppercase",
    lineHeight: 10,
  },
  tdNetMiniV: {
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 15,
  },
  tdEarningsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    marginBottom: 8,
    marginTop: 4,
  },
  tdEarningsHeaderTitle: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    lineHeight: 12,
  },
  tdBreakdownCard: {
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 4,
    gap: 2,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      default: { elevation: 2 },
    }),
  },
  tdBreakRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 10,
    gap: 8,
    borderRadius: 10,
    minHeight: 52,
  },
  tdBreakRowHighlight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 10,
    gap: 8,
    borderRadius: 10,
    marginVertical: 1,
    minHeight: 52,
  },
  tdBreakLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  tdBreakIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  tdBreakTitle: {
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  tdBreakTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 1,
  },
  tdBreakSub: {
    fontSize: 9,
    fontWeight: "500",
    marginTop: 1,
    lineHeight: 12,
  },
  tdBreakValue: {
    fontSize: 12,
    fontWeight: "800",
    flexShrink: 0,
    textAlign: "right",
    lineHeight: 16,
  },
  tdActiveBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  tdActiveBadgeText: {
    fontSize: 7,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: "#ffffff",
    textTransform: "uppercase",
    lineHeight: 10,
  },
  tdSettledBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    marginBottom: 10,
    backgroundColor: "#0f172a",
    minHeight: 56,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
      },
      default: { elevation: 3 },
    }),
  },
  tdSettledLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  tdSettledCalWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    flexShrink: 0,
  },
  tdSettledK: {
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: "rgba(148,163,184,0.95)",
    textTransform: "uppercase",
    marginBottom: 2,
    lineHeight: 11,
  },
  tdSettledV: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.1,
    lineHeight: 16,
  },
  tdSettledExport: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.12)",
    minWidth: 40,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  tdQueryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 44,
  },
  tdQueryBtnText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    lineHeight: 12,
  },
  detailHeaderLabelRef: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 2,
    lineHeight: 11,
    textTransform: "uppercase",
  },
  detailHeaderIdRowRef: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  detailHeaderDotRef: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  detailTitleRef: {
    fontSize: 14,
    fontWeight: "700",
    color: DETAIL_REF.headerTitle,
    letterSpacing: 0.1,
    lineHeight: 18,
  },
  detailTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailArchiveIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  detailSubtitleRef: {
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginTop: 1,
  },
  detailBackSpacer: {
    width: 40,
  },
  detailScrollRef: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    backgroundColor: DETAIL_REF.pageBg,
    ...Platform.select({
      web: { height: "100%" as unknown as number },
      default: {},
    }),
  },
  detailContentRef: {
    paddingTop: 12,
    paddingBottom: 72,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    flexGrow: 0,
  },
}),
);
