import { Platform, StyleSheet } from "react-native";
import Layout from "@pulse/core/constants/Layout";
import Theme from "@pulse/core/constants/Theme";

/** Ink accent — matches Theme.primary / create-trip desktop chrome. */
export const WIZARD_ACCENT = Theme.primary;
export const WIZARD_ACCENT_SOFT = "rgba(15, 23, 42, 0.06)";
export const WIZARD_ACCENT_BORDER = "rgba(15, 23, 42, 0.28)";
export const WIZARD_ACCENT_MUTED = "rgba(248, 250, 252, 0.95)";
/** Avatar size for wizard context rows + 2-col selection tiles (attribution parity). */
export const WIZARD_PARTY_AVATAR_SIZE = 34;
/** Party selection grids on compact / mobile layouts. */
export const WIZARD_PARTY_GRID_COLUMNS = 2;
/** Desktop party picker — four tiles per row (create trip / attribution parity). */
export const WIZARD_PARTY_GRID_COLUMNS_DESKTOP = 4;

/** Shared light full-page wizard chrome (attribution / create trip / load / allocation). */
export const fullPageWizardStyles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignItems: "center",
    backgroundColor: Theme.screenBackground,
  },
  shellKeyboard: {
    flex: 1,
    width: "100%",
    minHeight: 0,
  },
  pageRoot: {
    flex: 1,
    minHeight: 0,
    position: "relative",
    paddingHorizontal: 16,
    gap: 12,
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
    /** Keep header/body/footer in viewport — body scrolls, footer stays docked. */
    overflow: "hidden",
  },
  /** Inside desktop insight frame — main column fills rail layout. */
  pageRootInFrame: {
    maxWidth: "100%",
    alignSelf: "stretch",
  },
  /** Enterprise desktop — denser chrome, scrollable multi-section form. */
  pageRootDesktopForm: {
    gap: 10,
    paddingHorizontal: 0,
  },
  /** Mobile / narrow stepped wizard — full-width, compact chrome. */
  pageRootMobileFull: {
    maxWidth: "100%",
    width: "100%",
    alignSelf: "stretch",
    paddingHorizontal: Layout.screenPaddingHorizontal,
    gap: 10,
  },
  /**
   * Keypad steps: no side padding so the GPay dock can go edge-to-edge.
   * Header / progress / amount / footer re-apply Layout.screenPaddingHorizontal.
   */
  pageRootKeypad: {
    gap: 6,
    maxWidth: 720,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 0,
  },
  headerBarKeypad: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  progressPadKeypad: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  footerDockKeypad: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  /** Action bar seated above the numeric pad (keypad steps). */
  footerDockKeypadInline: {
    flexShrink: 0,
    width: "100%",
    paddingTop: 0,
    minHeight: 0,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    borderTopWidth: 0,
    backgroundColor: "transparent",
    shadowOpacity: 0,
    elevation: 0,
  },
  /** Sticky action dock — never clipped by page scroll / overflow. */
  footerDock: {
    flexShrink: 0,
    width: "100%",
    backgroundColor: Theme.cardWhite,
    zIndex: 40,
  },
  footerDockMobile: {
    paddingTop: 4,
    minHeight: 52,
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: -2 },
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  /** Absolute dock — Route/Load/etc. cannot push CTAs below the fold on RN Web. */
  footerDockMobilePinned: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    zIndex: 50,
  },
  /** Desktop stepped allocation / reassign — matches Create Trip rail width. */
  pageRootSteppedDesktop: {
    gap: 12,
    maxWidth: 1680,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 32,
  },
  pageHeaderBlock: {
    gap: 4,
    flexShrink: 0,
    marginTop: 2,
  },
  pageHeaderBlockKeypad: {
    gap: 2,
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 44,
    width: "100%",
    flexShrink: 0,
  },
  headerBarMobile: {
    minHeight: 44,
  },
  headerBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    flexShrink: 0,
  },
  headerBackBtnMobile: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 44,
    borderRadius: 12,
    gap: 6,
  },
  headerBackBtnText: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "600",
  },
  headerBackBtnTextMobile: {
    fontSize: 13,
  },
  headerStepBadge: {
    flexShrink: 0,
    minWidth: 88,
    alignItems: "flex-end",
  },
  headerStepBadgeSpacer: {
    minWidth: 88,
  },
  headerStepText: {
    color: Theme.textRouteCard,
    fontSize: 10,
    fontWeight: "600",
    backgroundColor: Theme.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
  },
  headerStepTextMobile: {
    fontSize: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  headerTitleCluster: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  titleInline: {
    color: Theme.textPrimaryDark,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 20,
    textAlign: "center",
  },
  titleInlineMobile: {
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.2,
  },
  titleInlineKeypad: {
    fontSize: 14,
    lineHeight: 18,
  },
  title: {
    color: Theme.textPrimaryDark,
    fontSize: 20,
    fontWeight: "800",
  },
  titleKeypad: {
    fontSize: 18,
    lineHeight: 24,
  },
  subtitle: {
    color: Theme.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    textAlign: "center",
  },
  subtitleMobile: {
    fontSize: 12,
    lineHeight: 16,
  },
  subtitleKeypad: {
    fontSize: 12,
    lineHeight: 17,
  },
  wizardStepTrackWrap: {
    width: "100%",
    position: "relative",
    paddingHorizontal: 2,
    paddingTop: 2,
    paddingBottom: 0,
    flexShrink: 0,
  },
  wizardStepTrackWrapMobile: {
    paddingTop: 0,
    paddingBottom: 2,
  },
  wizardStepTrack: {
    position: "absolute",
    left: "10%",
    right: "10%",
    top: 11,
    height: 1.5,
    backgroundColor: Theme.borderLight,
    borderRadius: 999,
    zIndex: 0,
    overflow: "hidden",
  },
  wizardStepTrackMobile: {
    top: 10,
  },
  wizardStepTrackFill: {
    height: "100%",
    backgroundColor: Theme.positive,
    borderRadius: 999,
    ...Platform.select({
      web: {
        transitionProperty: "width",
        transitionDuration: "0.3s",
        transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
      } as object,
      default: {},
    }),
  },
  wizardStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    width: "100%",
    zIndex: 1,
  },
  wizardStepItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    paddingHorizontal: 1,
  },
  wizardStepItemMobile: {
    gap: 4,
  },
  wizardStepCircle: {
    width: 22,
    height: 22,
    borderRadius: 7,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  wizardStepCircleMobile: {
    width: 22,
    height: 22,
    borderRadius: 7,
  },
  wizardStepCircleActive: {
    backgroundColor: Theme.accentBrown,
    borderColor: Theme.accentBrown,
  },
  wizardStepCircleDone: {
    backgroundColor: Theme.positive,
    borderColor: Theme.positive,
  },
  wizardStepCircleActiveRing: {
    borderWidth: 2,
    borderColor: Theme.surfaceBorder,
  },
  wizardStepCircleDoneRing: {
    borderWidth: 2,
    borderColor: Theme.positiveMuted,
  },
  wizardStepCircleText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  wizardStepCircleTextMobile: {
    fontSize: 10,
  },
  wizardStepCircleTextActive: {
    color: Theme.textOnPrimary,
  },
  wizardStepText: {
    fontSize: 8,
    color: Theme.textMuted,
    fontWeight: "600",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.2,
    lineHeight: 10,
  },
  wizardStepTextMobile: {
    fontSize: 9,
    letterSpacing: 0.2,
    lineHeight: 11,
  },
  wizardStepTextActive: {
    color: Theme.accentBrown,
    fontWeight: "700",
  },
  wizardStepTextDone: {
    color: Theme.positive,
    fontWeight: "700",
  },
  bodyScroll: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minHeight: 0,
    width: "100%",
  },
  bodyScrollContent: {
    gap: 12,
    paddingBottom: 16,
    flexGrow: 0,
  },
  bodyScrollContentMobile: {
    gap: 10,
    paddingBottom: 20,
  },
  bodyFill: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minHeight: 0,
    width: "100%",
    gap: 0,
  },
  /** ScrollView content for keypad fill body: fills when there's room, scrolls on overflow. */
  bodyFillScrollContent: {
    flexGrow: 1,
    width: "100%",
  },
  bodyWide: {
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
  },
  /** Flat step content — no nested card chrome inside the wizard shell. */
  wizardStepContentFlat: {
    width: "100%",
    gap: 12,
    paddingBottom: 4,
  },
  partyRow: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
    alignSelf: "stretch",
    alignItems: "stretch",
  },
  partyRowStack: {
    flexDirection: "column",
  },
  partyCard: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
    backgroundColor: Theme.cardWhite,
    paddingVertical: 12,
    paddingHorizontal: 12,
    minHeight: 64,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  partyCardPressable: {
    borderColor: Theme.borderLight,
    backgroundColor: "transparent",
  },
  /** Hit target wrapping partyCardFlat — keep card height + center content. */
  partyCardPressableHit: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  partyChangeIcon: {
    flexShrink: 0,
    marginLeft: 2,
    alignSelf: "center",
  },
  /** Full-width selectable party tile inside 2-col wizard grids. */
  partyCardSelectable: {
    width: "100%",
    alignSelf: "stretch",
  },
  partyCardSelected: {
    backgroundColor: Theme.cardWhite,
    borderWidth: 2,
    borderColor: Theme.textPrimaryDark,
  },
  /** Embedded allocation picker rows — light outline, no fill. */
  partyCardFlat: {
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    minHeight: 64,
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
  },
  /** Allocation text steps — tiny summary chips so the field stays readable. */
  partyCardFlatCompact: {
    paddingVertical: 4,
    paddingHorizontal: 7,
    minHeight: 32,
    borderRadius: 8,
    gap: 6,
  },
  /**
   * Horizontal scroll strip chip — content-sized (not flex:1) so labels
   * never collapse under the active field.
   */
  partyCardFlatStrip: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: "auto",
    maxWidth: 148,
    minWidth: 88,
    minHeight: 28,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 7,
    gap: 5,
    alignSelf: "center",
  },
  /** Solo party chip (no row sibling) — fill chrome width. */
  partyCardFlatSolo: {
    flex: 0,
    width: "100%",
  },
  partyCardFlatSelected: {
    backgroundColor: WIZARD_ACCENT_SOFT,
    borderColor: WIZARD_ACCENT,
  },
  partyTextWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    gap: 2,
  },
  partyTextWrapStrip: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    maxWidth: 108,
    gap: 0,
  },
  partyLabel: {
    color: Theme.textMuted,
    fontSize: 10,
    lineHeight: 13,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    fontWeight: "700",
    ...Platform.select({
      android: { includeFontPadding: false as const },
      default: {},
    }),
  },
  partyLabelCompact: {
    fontSize: 8,
    lineHeight: 10,
    letterSpacing: 0.3,
  },
  partyLabelStrip: {
    fontSize: 7,
    lineHeight: 9,
    letterSpacing: 0.2,
    fontWeight: "600",
  },
  partyName: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 17,
    ...Platform.select({
      android: { includeFontPadding: false as const },
      default: {},
    }),
  },
  partyNameCompact: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
  },
  partyNameStrip: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
  },
  partySubtitle: {
    color: Theme.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    ...Platform.select({
      android: { includeFontPadding: false as const },
      default: {},
    }),
  },
  block: {
    backgroundColor: Theme.cardWhite,
    padding: 12,
    gap: 8,
  },
  blockTitle: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "600",
  },
  blockLine: {
    color: Theme.textPrimaryDark,
    fontSize: 12,
    fontWeight: "500",
  },
  blockMeta: {
    color: Theme.textSecondary,
    fontSize: 12,
  },
  modeRow: {
    flexDirection: "row",
    gap: 4,
    width: "100%",
    alignSelf: "stretch",
    backgroundColor: Theme.surfaceGray,
    borderRadius: 12,
    padding: 3,
  },
  modeChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 36,
    backgroundColor: "transparent",
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  modeChipActive: {
    backgroundColor: Theme.cardWhite,
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOpacity: 0.08,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 1 },
      },
      android: { elevation: 1 },
      default: {},
    }),
  },
  modeChipText: {
    fontSize: 13,
    color: Theme.textMuted,
    fontWeight: "600",
  },
  modeChipTextActive: {
    color: Theme.textPrimaryDark,
    fontWeight: "700",
  },
  footerRoot: {
    width: "100%",
  },
  footerRootMobile: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
    paddingTop: 4,
  },
  footerHintAbove: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    textAlign: "center",
    lineHeight: 15,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  footerHintAboveMobile: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: "left",
    paddingHorizontal: 2,
    paddingBottom: 8,
    color: Theme.textSecondary,
  },
  footerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
    paddingTop: 12,
    paddingBottom: 2,
    flexWrap: "nowrap",
  },
  /** Mobile: Close + full-width Continue share one row — Continue never clips. */
  footerBarMobile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "100%",
    paddingTop: 8,
    paddingBottom: 2,
    borderTopWidth: 0,
  },
  footerBarWithSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
    paddingTop: 12,
    paddingBottom: 2,
  },
  /** Keeps Close / Confirm (etc.) grouped on the right next to each other. */
  footerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
    marginLeft: "auto",
  },
  footerBackSpacer: {
    minWidth: 88,
  },
  footerInlineHint: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    flexShrink: 1,
    maxWidth: 120,
    textAlign: "right",
    lineHeight: 14,
  },
  footerSummary: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    textAlign: "center",
    lineHeight: 15,
    marginBottom: 4,
  },
  footerSummaryInline: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textMuted,
    textAlign: "left",
    lineHeight: 18,
    paddingRight: 8,
  },
  cancelBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minWidth: 96,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  cancelBtnMobile: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minWidth: 84,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    flexShrink: 0,
  },
  cancelBtnText: {
    color: Theme.textRouteCard,
    fontSize: 13,
    fontWeight: "600",
  },
  cancelBtnTextMobile: {
    color: Theme.textRouteCard,
    fontSize: 13,
    fontWeight: "600",
  },
  /** Match OperationalButton primary — pastel fill + ink border (not borderless wash). */
  submitBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 132,
    maxWidth: 220,
    backgroundColor: Theme.buttonPrimary,
    borderWidth: Theme.buttonPrimaryBorderWidth,
    borderColor: Theme.buttonPrimaryBorder,
    paddingHorizontal: 18,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 14,
  },
  /** Solid brown CTA — brand ink on light wizard shells (Create Load / Create Trip). */
  submitBtnInk: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 140,
    maxWidth: 240,
    backgroundColor: Theme.accentBrown,
    paddingHorizontal: 22,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.accentBrownDeep,
  },
  /** Mobile primary CTA — fills remaining row width so it never clips off-screen. */
  submitBtnMobileGrow: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    maxWidth: "100%",
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  submitBtnInkDisabled: {
    backgroundColor: Theme.surfaceGray,
    borderColor: Theme.borderMedium,
  },
  submitBtnInkText: {
    color: Theme.textOnPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  submitBtnInkTextDisabled: {
    color: Theme.textSecondary,
  },
  submitBtnWithSummary: {
    flexShrink: 0,
  },
  submitBtnDisabled: {
    opacity: 1,
    backgroundColor: Theme.surface,
    borderColor: Theme.borderMedium,
  },
  submitBtnText: {
    color: Theme.buttonPrimaryText,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
    ...Platform.select({
      android: { includeFontPadding: false as const },
      default: {},
    }),
  },
  submitBtnTextDisabled: {
    color: Theme.textMuted,
  },
  tertiaryBtn: {
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  tertiaryBtnDisabled: {
    opacity: 0.5,
  },
  tertiaryBtnText: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "700",
  },
  footerHint: {
    color: Theme.textMuted,
    fontSize: 12,
    lineHeight: 16,
    textAlign: "center",
    marginTop: 8,
  },
  /** Form section card — matches wizard block styling inside step bodies. */
  formSectionCard: {
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 8,
  },
  formSectionTitle: {
    color: Theme.textPrimaryDark,
    fontSize: 14,
    fontWeight: "700",
  },
  formSectionSubtitle: {
    color: Theme.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  formLabel: {
    color: Theme.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
  },
  formInput: {
    backgroundColor: Theme.screenBackground,
    color: Theme.textPrimaryDark,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  clientListWrap: {
    backgroundColor: Theme.screenBackground,
    overflow: "hidden",
  },
  /** Two-column attribution-style entity picker grid. */
  selectionGridWrap: {
    width: "100%",
    alignSelf: "stretch",
  },
  wizardPickerListShell: {
    width: "100%",
    alignSelf: "stretch",
    backgroundColor: Theme.screenBackground,
    overflow: "hidden",
    padding: 0,
  },
  wizardPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    width: "100%",
  },
  wizardPickerHeaderEmbedded: {
    paddingTop: 2,
    marginBottom: 2,
  },
  wizardPickerTitle: {
    flex: 1,
    minWidth: 0,
    color: Theme.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.45,
    textTransform: "uppercase",
  },
  wizardPickerCountBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: WIZARD_ACCENT_SOFT,
    flexShrink: 0,
  },
  wizardPickerCountBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    color: WIZARD_ACCENT,
  },
  wizardPickerFooterHint: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    color: Theme.textMuted,
    textAlign: "left",
    marginTop: 4,
  },
  wizardPickerSecondaryBtn: {
    alignSelf: "stretch",
    minHeight: 44,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  wizardPickerSecondaryBtnText: {
    color: WIZARD_ACCENT,
    fontSize: 12,
    fontWeight: "700",
  },
  selectionGridScrollContent: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  selectionGridScrollContentFlat: {
    paddingVertical: 4,
    paddingHorizontal: 0,
    paddingBottom: 4,
  },
  selectionGrid: {
    gap: 10,
    width: "100%",
  },
  selectionGridRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
    width: "100%",
  },
  selectionGridCell: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
  },
  selectionGridTile: {
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: Theme.cardWhite,
    paddingVertical: 10,
    paddingHorizontal: 6,
    minHeight: 108,
  },
  selectionGridTileSelected: {
    backgroundColor: WIZARD_ACCENT_SOFT,
  },
  selectionGridCheckParty: {
    right: -4,
    bottom: -4,
    width: 16,
    height: 16,
  },
  selectionGridTileDisabled: {
    opacity: 0.55,
  },
  selectionGridAvatarWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  selectionGridCheck: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 18,
    height: 18,
    backgroundColor: WIZARD_ACCENT,
    alignItems: "center",
    justifyContent: "center",
  },
  selectionGridName: {
    marginTop: 8,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    color: Theme.textPrimaryDark,
    textAlign: "center",
    width: "100%",
    paddingHorizontal: 2,
  },
  selectionGridNameCompact: {
    marginTop: 6,
    fontSize: 10,
    lineHeight: 13,
  },
  selectionGridNameDisabled: {
    color: Theme.textMuted,
  },
  selectionGridMeta: {
    marginTop: 2,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "500",
    color: Theme.textSecondary,
    textAlign: "center",
    width: "100%",
    paddingHorizontal: 2,
  },
  selectionGridMetaWarn: {
    color: Theme.warning,
    fontWeight: "700",
  },
  clientLoadingWrap: {
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  clientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.borderLight,
  },
  clientRowSelected: {
    backgroundColor: WIZARD_ACCENT_SOFT,
    borderLeftWidth: 2,
    borderLeftColor: WIZARD_ACCENT,
  },
  /** Horizontal shipper / client row — attribution picker style. */
  shipperMarkCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Theme.screenBackground,
    padding: 10,
  },
  shipperMarkCardFlat: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 56,
  },
  shipperWarningCard: {
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  shipperWarningText: {
    color: Theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  addClientBtn: {
    alignSelf: "stretch",
    minHeight: 44,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  addClientBtnText: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "700",
  },
  addClientBtnFlat: {
    backgroundColor: Theme.cardWhite,
    minHeight: 44,
    paddingVertical: 10,
    marginTop: 2,
  },
  /** Wizard step field label — matches attribution block titles. */
  wizardFieldLabel: {
    color: Theme.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
    marginBottom: 6,
    marginTop: 2,
  },
  /** Wizard step text input — readable body size for mobile. */
  wizardFieldInput: {
    backgroundColor: Theme.cardWhite,
    color: Theme.textPrimaryDark,
    fontSize: 18,
    fontWeight: "600",
    fontStyle: "normal",
    lineHeight: 24,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 12 : 10,
    minHeight: 48,
    height: 48,
    marginBottom: 0,
    width: "100%",
    alignSelf: "stretch",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    textAlignVertical: "center",
    ...Platform.select({
      web: {
        outlineStyle: "none",
        // RN-web: keep typed value visible (avoid clipped tall box).
        boxSizing: "border-box",
      } as object,
      android: { includeFontPadding: false as const },
      default: {},
    }),
  },
  wizardStepBody: {
    width: "100%",
    gap: 14,
    paddingBottom: 8,
  },
  /**
   * Keypad allocate steps: pageRootKeypad has no side pad — chrome above the
   * pad (context row, priors, mode) must re-apply the same inset as header.
   */
  wizardKeypadChromePad: {
    width: "100%",
    flexShrink: 0,
    gap: 8,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingBottom: 8,
    marginBottom: 4,
    backgroundColor: Theme.screenBackground,
    zIndex: 2,
  },
  /** Flex host for keypad step content under chrome (fill remaining height). */
  wizardKeypadStepFill: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    zIndex: 1,
  },
  /** Prior-step summary cards in one row above the active field. */
  wizardPriorSelectionsStack: {
    width: "100%",
    gap: 6,
    marginBottom: 2,
  },
  wizardPriorSelectionsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 6,
    width: "100%",
  },
  wizardPriorSelectionCell: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
  },
  wizardPriorSelectionCard: {
    width: "100%",
    alignSelf: "stretch",
    padding: 8,
    gap: 8,
  },
  wizardPriorSelectionCardCompact: {
    padding: 0,
    gap: 0,
    flex: 1,
    minWidth: 0,
  },
  /** Single compact summary strip — horizontal scroll for shipper · rate · phone … */
  wizardSummaryStrip: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
    maxHeight: 40,
    marginBottom: 0,
  },
  wizardSummaryStripContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 2,
    paddingRight: 8,
  },
  wizardSummaryStripCell: {
    flexGrow: 0,
    flexShrink: 0,
  },
  wizardFieldBlock: {
    width: "100%",
    gap: 6,
    marginTop: 4,
  },
  /** Flat list block — no outer card when parent already uses formSectionCard. */
  blockFlat: {
    width: "100%",
    alignSelf: "stretch",
    gap: 10,
  },
  blockFlatEmbedded: {
    gap: 10,
  },
  wizardPickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    backgroundColor: Theme.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  wizardPickerBtnEmpty: {
    borderStyle: "dashed",
  },
  wizardPickerBtnText: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    lineHeight: 20,
  },
  wizardPickerBtnPlaceholder: {
    color: Theme.textMuted,
    fontWeight: "500",
  },
  wizardDateTouchable: {
    minHeight: 44,
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  wizardDateText: {
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
  wizardDatePlaceholder: {
    fontSize: 14,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  quickDateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickDateChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: Theme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  quickDateChipActive: {
    backgroundColor: Theme.accentBrown,
    borderColor: Theme.accentBrownDeep,
  },
  quickDateChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  quickDateChipTextActive: {
    color: Theme.textOnPrimary,
    fontWeight: "700",
  },
  /** Pay-style centered numeric entry inside wizard shell (GPay payout parity). */
  wizardKeypadRoot: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
  },
  /** Full-screen allocate rates/phone — root fills shell; dock pins to bottom. */
  wizardKeypadRootFill: {
    position: "relative",
    flex: 1,
    minHeight: 0,
  },
  /**
   * Desktop rate/sale popup — hug content.
   * Must set `flex: 0` (not only flexGrow) so RN Web’s `flex: 1` shorthand
   * from wizardKeypadRoot does not keep growing the sheet and leave a dead
   * white gap under the keypad.
   */
  wizardKeypadRootPopup: {
    flex: 0,
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minHeight: 0,
    width: "100%",
    alignSelf: "stretch",
  },
  wizardKeypadBody: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 12,
    paddingTop: 2,
  },
  /** Mobile GPay — amount up top; CTA+pad dock pinned below. */
  wizardKeypadBodyMobilePay: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    justifyContent: "flex-start",
    gap: 10,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingBottom: 8,
    paddingTop: 8,
  },
  /**
   * Reserve space for absolute CTA + default pay pad
   * (≈56 CTA + 4×54 keys + row gaps + dock chrome).
   */
  wizardKeypadBodyFillPad: {
    /** Room for Continue + default pay pad (match client-sale fill). */
    paddingBottom: 380,
  },
  /** Reserved when a dock accessory is used above the pad. */
  wizardKeypadBodyFillPadTall: {
    paddingBottom: 420,
  },
  wizardKeypadBodyCompact: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    gap: 8,
    paddingTop: 4,
    justifyContent: "flex-start",
  },
  /** Desktop rate/sale popup — stack from the top like driver sign-in. */
  wizardKeypadBodyPopup: {
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    justifyContent: "flex-start",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 4,
  },
  /** Popup: hug content in one column — no flex fill, no overlap with the pad. */
  wizardKeypadBodyPopupStack: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 10,
    alignItems: "center",
  },
  /** Popup body — room for party + field switch + amount (partner rate). */
  wizardKeypadBodyScrollPopup: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minHeight: 0,
    maxHeight: 320,
  },
  /** Keep the ₹ amount from collapsing under party / field chrome. */
  wizardKeypadAmountAnchor: {
    width: "100%",
    flexShrink: 0,
    alignItems: "center",
  },
  wizardKeypadAmountAnchorPopup: {
    minHeight: 72,
    justifyContent: "center",
  },
  wizardKeypadPartyWrap: {
    alignSelf: "stretch",
    width: "100%",
    flexShrink: 0,
  },
  /** GPay centered recipient (avatar → name → phone). */
  wizardKeypadRecipientWrap: {
    alignSelf: "stretch",
    width: "100%",
    flexShrink: 0,
    alignItems: "center",
  },
  wizardKeypadAccessory: {
    width: "100%",
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingTop: 6,
    paddingBottom: 4,
    flexShrink: 0,
    alignItems: "center",
  },
  wizardKeypadAccessoryPopup: {
    paddingHorizontal: 0,
    paddingTop: 4,
    paddingBottom: 4,
  },
  /** Margin % chips etc. — sit directly above the number pad in the pinned dock. */
  wizardKeypadDockAccessory: {
    width: "100%",
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingTop: 4,
    paddingBottom: 8,
    flexShrink: 0,
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
  },
  wizardKeypadDockAccessoryPopup: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 6,
    borderTopWidth: 0,
  },
  wizardKeypadBottomDock: {
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
    backgroundColor: Theme.cardWhite,
    zIndex: 6,
  },
  /** True mobile: glue Continue + keys to the bottom of the fill shell. */
  wizardKeypadBottomDockPinned: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    marginTop: 0,
  },
  wizardKeypadBottomDockPopup: {
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
    marginTop: 0,
    paddingTop: 4,
    gap: 0,
  },
  wizardKeypadPadDock: {
    marginTop: 0,
  },
  /** Isolated pad tray — never share fill-shell `marginTop: auto` / zero padding. */
  wizardKeypadPadDockPopup: {
    width: "100%",
    marginTop: 0,
    paddingTop: 14,
    paddingBottom: 14,
    paddingHorizontal: 12,
    backgroundColor: Theme.surfaceGray,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  wizardKeypadActionBar: {
    flexShrink: 0,
    width: "100%",
    zIndex: 5,
    backgroundColor: Theme.cardWhite,
    paddingTop: 4,
    /** Match PhoneNumberKeypadFlow — full-bleed CTA above pad, pad owns side inset. */
    paddingHorizontal: 0,
  },
  wizardKeypadDesktopActionBar: {
    flexShrink: 0,
    width: "100%",
    maxWidth: 640,
    marginTop: 12,
    zIndex: 5,
  },
  wizardKeypadPartyCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 14,
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
      },
      android: { elevation: 2 },
      web: {
        boxShadow: "0 4px 16px rgba(15, 23, 42, 0.06)",
      } as object,
      default: {},
    }),
  },
  wizardKeypadFieldSwitch: {
    alignSelf: "stretch",
    width: "100%",
    maxWidth: 360,
    flexShrink: 0,
  },
  wizardKeypadFieldSwitchCompact: {
    maxWidth: 320,
  },
  modeChipCompact: {
    minHeight: 30,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  modeChipTextCompact: {
    fontSize: 11,
    fontWeight: "600",
  },
  wizardKeypadDesktopSwitch: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: Theme.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.borderLight,
  },
  wizardKeypadPayoutStage: {
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  wizardKeypadPayoutStageCompact: {
    flex: 0,
    flexGrow: 0,
    justifyContent: "flex-start",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  wizardKeypadLabelBlock: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 4,
    width: "100%",
  },
  wizardKeypadTitle: {
    color: Theme.textPrimaryDark,
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: -0.2,
  },
  wizardKeypadTitleCompact: {
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    letterSpacing: -0.15,
    textAlign: "center",
    color: Theme.textPrimaryDark,
    width: "100%",
  },
  wizardKeypadHint: {
    color: Theme.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 8,
    maxWidth: 300,
  },
  wizardKeypadHintMuted: {
    color: Theme.textMuted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 12,
    maxWidth: 280,
    minHeight: 15,
  },
  wizardKeypadError: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.destructive,
    textAlign: "center",
    paddingHorizontal: 12,
    minHeight: 18,
  },
  wizardKeypadErrorSpacer: {
    minHeight: 8,
  },
  /** Desktop: unified card — client, amount, and keypad as one surface. */
  wizardKeypadDesktopCenter: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
  },
  wizardKeypadDesktopCard: {
    width: "100%",
    maxWidth: 640,
    backgroundColor: Theme.cardWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
    elevation: 3,
  },
  wizardKeypadPartyInCard: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.borderLight,
    backgroundColor: Theme.surface,
  },
  wizardKeypadDesktopRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 0,
    minHeight: 280,
  },
  wizardKeypadAmountPane: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  wizardKeypadKeysPane: {
    width: 272,
    flexShrink: 0,
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  wizardKeypadKeysCard: {
    overflow: "hidden",
  },
  /** Full-width desktop wizard (no insight rails). */
  desktopFrameSingle: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    maxWidth: 1680,
    alignSelf: "center",
    alignItems: "stretch",
    paddingHorizontal: 24,
  },
  /** Narrow / phone — no side rail padding; pageRoot owns horizontal inset. */
  desktopFrameSingleMobile: {
    paddingHorizontal: 0,
  },
  desktopFrameRow: {
    flex: 1,
    width: "100%",
    maxWidth: 1680,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "stretch",
    gap: 16,
    paddingHorizontal: 24,
  },
  desktopFrameMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
  },
  desktopInsightRail: {
    width: 220,
    flexShrink: 0,
    gap: 12,
    paddingTop: 8,
  },
  desktopInsightRailLeft: {
    paddingRight: 4,
  },
  desktopInsightRailRight: {
    paddingLeft: 4,
  },
  desktopInsightRailRightStack: {
    width: 220,
    flexShrink: 0,
    gap: 12,
    paddingTop: 8,
  },
  desktopInsightRailHeading: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: Theme.textSecondary,
    marginBottom: 4,
  },
  desktopInsightCard: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
    overflow: "hidden",
    position: "relative",
    minHeight: 102,
  },
  desktopInsightCardSingle: {
    minHeight: 128,
    paddingVertical: 14,
    gap: 8,
  },
  desktopInsightWatermark: {
    position: "absolute",
    right: -10,
    bottom: -8,
    opacity: 0.07,
  },
  desktopInsightWatermarkSingle: {
    right: -6,
    bottom: -4,
    opacity: 0.09,
  },
  desktopInsightEyebrow: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: WIZARD_ACCENT,
  },
  desktopInsightTitle: {
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
    color: Theme.textPrimaryDark,
  },
  desktopInsightBody: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    color: Theme.textSecondary,
  },
  desktopContextPanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 6,
  },
  desktopContextEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.45,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  desktopContextTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    lineHeight: 18,
  },
  desktopContextLine: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    color: Theme.textSecondary,
  },
});
