import { Platform, StyleSheet } from "react-native";

import Layout from "@pulse/core/constants/Layout";
import Theme from "@pulse/core/constants/Theme";
import Typography from "@pulse/core/constants/Typography";

/** Compact icon sizes for driver expense / odometer ops flows. */
export const DriverOpsEntryIcon = {
  back: 15,
  headerAction: 12,
  headerThumb: 12,
  hero: 15,
  notice: 12,
  chip: 14,
  chipPill: 10,
  scanBanner: 13,
  scanConfirm: 11,
  photoEmpty: 18,
} as const;

export const driverOpsEntryStyles = StyleSheet.create({
  header: {
    flexShrink: 0,
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingBottom: 8,
    gap: 6,
    zIndex: 3,
    elevation: 3,
    position: "relative",
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  backText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#fff",
  },
  attachCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
  },
  attachBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    minHeight: 32,
  },
  attachBtnSecondary: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.2)",
  },
  attachBtnText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
    letterSpacing: 0.15,
  },
  attachThumbBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.85)",
  },
  attachThumbBtnScanning: {
    borderColor: "#6ee7b7",
    shadowColor: "#6ee7b7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.85,
    shadowRadius: 4,
  },
  attachThumb: {
    width: "100%",
    height: "100%",
  },
  attachRemoveBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  headerScanBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    minHeight: 32,
  },
  headerScanBtnText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  heroIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  heroKicker: {
    ...Typography.headerTitle,
    fontSize: 9,
    letterSpacing: 0.7,
    color: "rgba(255,255,255,0.72)",
  },
  heroTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -0.25,
  },
  routeInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 1,
    minWidth: 0,
  },
  routeInlineText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "600",
    lineHeight: 13,
    color: "rgba(255,255,255,0.82)",
  },
  heroHint: {
    fontSize: 10,
    fontWeight: "500",
    lineHeight: 14,
    color: "rgba(255,255,255,0.72)",
  },
  content: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingTop: 10,
    gap: 10,
  },
  section: {
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 12,
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
      },
      android: { elevation: 1 },
      default: {},
    }),
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 0,
  },
  sectionAccent: {
    // Kept for callers that may still reference it; unused on expense form.
    width: 0,
    height: 0,
  },
  sectionTitle: {
    ...Typography.headerTitle,
    fontSize: 10,
    letterSpacing: 0.55,
    fontWeight: "700",
  },
  sectionBody: {
    gap: 10,
  },
  fieldDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
    marginVertical: 2,
    opacity: 0.9,
  },
  fieldLabel: {
    ...Typography.headerTitle,
    fontSize: 11,
    letterSpacing: 0.45,
    marginBottom: 6,
    fontWeight: "700",
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: "500",
    minHeight: 44,
    lineHeight: 20,
  },
  inputMultiline: {
    minHeight: 72,
    textAlignVertical: "top",
    paddingTop: 10,
  },
  notice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
  },
  noticeText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },
  syncHint: {
    fontSize: 10,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 8,
  },
  footer: {
    flexShrink: 0,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    width: "100%",
  },
  skipBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
  },
  skipText: {
    fontSize: 13,
    fontWeight: "700",
  },
  saveBtn: {
    flex: 1.4,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    borderRadius: 10,
    ...Platform.select({
      ios: {
        shadowColor: Theme.driverEmeraldDark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  saveText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.15,
  },
});
