import {
  CHAT_ACCENT,
  CHAT_INCOMING_BUBBLE,
  CHAT_TEXT_PRIMARY,
} from "../../chatTheme";
import { SLACK_CHAT_AVATAR } from "../shared/chatSlackAvatar.constants";
import { Platform, StyleSheet } from "react-native";

import { withWebSafeShadows } from "@pulse/core/lib/platformViewStyle.util";

/** Pulse Chat — matte black chrome + indigo accent. */
export const PULSE_CHAT = {
  matteBlack: "#181C32",
  matteBlackSoft: "#1E2139",
  matteBlackDeep: "#13151F",
  headerActionBg: "rgba(255,255,255,0.07)",
  headerActionBorder: "rgba(255,255,255,0.1)",
  headerHairline: "rgba(255,255,255,0.08)",
  accent: CHAT_ACCENT,
  accentSoft: "rgba(91, 94, 244, 0.14)",
  accentGlow: "rgba(91, 94, 244, 0.35)",
} as const;

/** Slack-density mobile inbox typography + chrome. */
export const SLACK_MOBILE = {
  headerBg: PULSE_CHAT.matteBlack,
  headerTitleColor: "#FFFFFF",
  chipActiveBg: PULSE_CHAT.matteBlack,
  chipActiveText: "#FFFFFF",
  chipBorder: "#DDDDDD",
  chipText: "#616061",
  chipTextMuted: "#8B8B8B",
  fabBg: PULSE_CHAT.accent,
  threadPillBg: "#F4F4F4",
  onlineDot: "#2BAC76",
  listDivider: "#EBEBEB",
  searchBg: "#F4F4F4",
  textPrimary: "#1D1C1D",
  textSecondary: "#616061",
  textTertiary: "#8B8B8B",
  iconInactive: "#616061",
  iconActive: "#FFFFFF",
} as const;

/** Slack-accurate type scale — compact, not heavy. */
export const SLACK_TYPE = {
  headerTitle: 18,
  brandDot: 18,
  listTitle: 12,
  listPreview: 11,
  listTime: 9,
  peopleName: 10,
  filterChip: 11,
  searchInput: 14,
  threadTitle: 13,
  threadSubtitle: 10,
  msgName: 13,
  msgTime: 11,
  msgBody: 14,
  composerInput: 14,
  bottomNavLabel: 9,
  peopleSection: 10,
  headerSubtitle: 11,
} as const;

export const SLACK_ICON = {
  strokeInactive: 1.65,
  strokeActive: 2.1,
  strokeHeader: 2.25,
  sizeTab: 14,
  sizeFilter: 13,
  sizeSearch: 16,
  sizeBack: 22,
  sizeClose: 20,
  sizeFab: 20,
  sizeBottomNav: 18,
} as const;

export const SLACK_AVATAR = SLACK_CHAT_AVATAR;

/** Horizontal inset for people strip header, avatars, and empty state. */
export const PEOPLE_STRIP_PAD_H = 14;

/** Visible row height of the Slack-style bottom tab bar (excludes safe-area inset). */
export const CHAT_SLACK_BOTTOM_NAV_BAR = 48;

/** Shared FlatList tuning for responsive chat inbox scrolling. */
export const SLACK_CHAT_LIST_PROPS = {
  initialNumToRender: 14,
  maxToRenderPerBatch: 8,
  windowSize: 6,
  removeClippedSubviews: true,
  keyboardShouldPersistTaps: "handled" as const,
  showsVerticalScrollIndicator: false,
};

export const slackMobileStyles = withWebSafeShadows(
  StyleSheet.create({
  listScroll: {
    flex: 1,
    minHeight: 0,
  },
  listHeader: {
    position: "relative",
    backgroundColor: SLACK_MOBILE.headerBg,
    paddingHorizontal: 14,
    paddingBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PULSE_CHAT.headerHairline,
    overflow: "hidden",
  },
  listHeaderMirrorSheen: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: "none",
  },
  listHeaderMirrorGlow: {
    position: "absolute",
    left: "12%",
    right: "12%",
    top: 0,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.22)",
    borderRadius: 1,
  },
  listHeaderAccentLine: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 2.5,
    backgroundColor: PULSE_CHAT.accent,
    opacity: 0.55,
    shadowColor: PULSE_CHAT.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 6,
  },
  listHeaderTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
    marginLeft: 2,
  },
  listHeaderBrandRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  listHeaderTitle: {
    fontSize: SLACK_TYPE.headerTitle,
    fontWeight: "900",
    color: SLACK_MOBILE.headerTitleColor,
    letterSpacing: -0.4,
  },
  listHeaderBrandDot: {
    fontSize: SLACK_TYPE.brandDot,
    fontWeight: "900",
    color: PULSE_CHAT.accent,
    letterSpacing: -0.4,
    ...(Platform.OS === "web"
      ? { textShadow: `0px 0px 8px ${PULSE_CHAT.accentGlow}` }
      : {
          textShadowColor: PULSE_CHAT.accentGlow,
          textShadowOffset: { width: 0, height: 0 },
          textShadowRadius: 8,
        }),
  },
  listHeaderSubtitle: {
    fontSize: SLACK_TYPE.headerSubtitle,
    fontWeight: "700",
    color: "rgba(255,255,255,0.62)",
    letterSpacing: 0.75,
    textTransform: "uppercase",
  },
  listHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  listHeaderMirrorBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.09)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.16)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
    elevation: 2,
  },
  listHeaderActionBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.09)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.16)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
    elevation: 2,
  },
  listHeaderCloseBtn: {
    marginLeft: -2,
  },
  listHeaderAvatarWrap: {
    position: "relative",
    marginRight: 2,
    borderRadius: 999,
    padding: 2,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.92)",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    shadowColor: PULSE_CHAT.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 6,
    elevation: 3,
  },
  listHeaderOnlineDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: SLACK_MOBILE.onlineDot,
    borderWidth: 2,
    borderColor: PULSE_CHAT.matteBlack,
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 4,
    flexShrink: 0,
    backgroundColor: "#FFFFFF",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: SLACK_MOBILE.listDivider,
  },
  bottomNavPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#F4F4F4",
    borderRadius: 24,
    paddingHorizontal: 2,
    paddingVertical: 3,
    minHeight: CHAT_SLACK_BOTTOM_NAV_BAR,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 3,
    gap: 1,
    minWidth: 0,
  },
  bottomNavItemIconWrap: {
    position: "relative",
    width: 36,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  bottomNavItemIconWrapActive: {
    backgroundColor: PULSE_CHAT.accentSoft,
  },
  bottomNavItemLabel: {
    fontSize: SLACK_TYPE.bottomNavLabel,
    fontWeight: "500",
    color: SLACK_MOBILE.chipText,
    letterSpacing: 0.05,
  },
  bottomNavItemLabelActive: {
    color: PULSE_CHAT.accent,
    fontWeight: "600",
  },
  bottomNavBadge: {
    position: "absolute",
    top: -3,
    right: 4,
    minWidth: 13,
    height: 13,
    borderRadius: 7,
    paddingHorizontal: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PULSE_CHAT.accent,
  },
  bottomNavBadgeText: {
    fontSize: 7,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  bottomNavSearch: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  streamTabBadgeInactive: {
    backgroundColor: PULSE_CHAT.accent,
  },
  streamTabBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  peopleStrip: {
    backgroundColor: "#FFFFFF",
    alignSelf: "stretch",
    width: "100%",
  },
  peopleStripHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: PEOPLE_STRIP_PAD_H,
    paddingTop: 8,
    paddingBottom: 6,
  },
  peopleStripLabel: {
    fontSize: SLACK_TYPE.peopleSection,
    fontWeight: "600",
    color: SLACK_MOBILE.textTertiary,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  peopleStripHint: {
    fontSize: SLACK_TYPE.peopleSection,
    fontWeight: "500",
    color: PULSE_CHAT.accent,
  },
  peopleStripContent: {
    paddingHorizontal: PEOPLE_STRIP_PAD_H,
    paddingBottom: 12,
    gap: 10,
    alignItems: "flex-start",
  },
  peopleStripEmptyWrap: {
    alignSelf: "stretch",
    width: "100%",
    paddingHorizontal: PEOPLE_STRIP_PAD_H,
    paddingBottom: 12,
  },
  peopleStripEmptyCard: {
    alignItems: "center",
    alignSelf: "stretch",
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e8edf4",
  },
  peopleStripEmptyLottie: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  peopleStripEmptyTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: SLACK_MOBILE.textPrimary,
    letterSpacing: -0.15,
    textAlign: "center",
  },
  peopleStripEmptySubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: SLACK_MOBILE.textTertiary,
    lineHeight: 15,
    textAlign: "center",
    maxWidth: 280,
    alignSelf: "center",
  },
  peopleItem: {
    width: 64,
    alignItems: "center",
    gap: 6,
  },
  peopleNewTile: {
    width: SLACK_AVATAR.people,
    height: SLACK_AVATAR.people,
    borderRadius: SLACK_AVATAR.people / 2,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: SLACK_MOBILE.chipBorder,
    backgroundColor: "#FAFAFA",
    alignItems: "center",
    justifyContent: "center",
  },
  peopleNewAvatarWrap: {
    width: SLACK_AVATAR.people,
    height: SLACK_AVATAR.people,
    borderRadius: SLACK_AVATAR.people / 2,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 5,
  },
  peopleNewAvatarPlate: {
    width: SLACK_AVATAR.people - 6,
    height: SLACK_AVATAR.people - 6,
    borderRadius: (SLACK_AVATAR.people - 6) / 2,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  peopleNewAvatarImage: {
    width: SLACK_AVATAR.people - 8,
    height: SLACK_AVATAR.people - 8,
  },
  peopleNewBadge: {
    position: "absolute",
    right: -1,
    bottom: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#F4C542",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  peopleAvatarWrap: {
    position: "relative",
  },
  peopleAvatarRing: {
    borderRadius: 999,
    padding: 2,
    borderWidth: 2,
    borderColor: "transparent",
  },
  peopleAvatarRingUnread: {
    borderColor: PULSE_CHAT.accent,
  },
  peopleAvatarRingActive: {
    borderColor: PULSE_CHAT.accent,
    backgroundColor: PULSE_CHAT.accentSoft,
  },
  peopleAvatarCircle: {
    borderRadius: 999,
    overflow: "hidden",
  },
  peopleUnreadBadge: {
    position: "absolute",
    top: -2,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PULSE_CHAT.accent,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  peopleUnreadBadgeText: {
    fontSize: 8,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  peopleOnlineDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: SLACK_MOBILE.onlineDot,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  peopleOfflineDot: {
    backgroundColor: "#C1C1C1",
  },
  peopleName: {
    fontSize: SLACK_TYPE.peopleName,
    fontWeight: "500",
    color: SLACK_MOBILE.textSecondary,
    textAlign: "center",
    width: 64,
  },
  peopleNameActive: {
    color: SLACK_MOBILE.textPrimary,
    fontWeight: "600",
  },
  inboxChrome: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    marginTop: -12,
    paddingTop: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_MOBILE.listDivider,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    width: "100%",
    alignSelf: "stretch",
  },
  chromeDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: SLACK_MOBILE.listDivider,
    marginHorizontal: 14,
    marginTop: 2,
  },
  filterTrack: {
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 3,
    borderRadius: 18,
    backgroundColor: "#F4F4F4",
    borderWidth: 1,
    borderColor: "#ECECEC",
    alignSelf: "stretch",
    width: "100%",
    maxWidth: "100%",
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  filterChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "transparent",
    backgroundColor: "transparent",
    minWidth: 0,
  },
  filterChipActive: {
    backgroundColor: SLACK_MOBILE.chipActiveBg,
    borderColor: SLACK_MOBILE.chipActiveBg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
  },
  filterChipText: {
    fontSize: SLACK_TYPE.filterChip,
    fontWeight: "500",
    color: SLACK_MOBILE.chipText,
  },
  filterChipTextActive: {
    color: SLACK_MOBILE.chipActiveText,
    fontWeight: "600",
  },
  fab: {
    position: "absolute",
    right: 16,
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 8,
  },
  fabAvatarPlate: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  fabAvatarImage: {
    width: 46,
    height: 46,
  },
  fabBadge: {
    position: "absolute",
    right: -3,
    bottom: 1,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#F4C542",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
    minHeight: 64,
    backgroundColor: "#FFFFFF",
    borderLeftWidth: 3,
    borderLeftColor: "transparent",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_MOBILE.listDivider,
  },
  listRowWithMedia: {
    minHeight: 140,
    paddingVertical: 12,
  },
  listRowSeparator: {
    height: 0,
  },
  listRowPressed: {
    backgroundColor: "#F1F5F9",
  },
  listRowActive: {
    backgroundColor: "rgba(91, 94, 244, 0.05)",
    borderLeftColor: PULSE_CHAT.accent,
  },
  listRowAvatarWrap: {
    position: "relative",
    marginTop: 0,
  },
  listRowAvatarCircle: {
    borderRadius: 999,
    overflow: "hidden",
  },
  listRowUnreadDot: {
    position: "absolute",
    right: -1,
    top: -1,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: PULSE_CHAT.accent,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  listRowBody: {
    flex: 1,
    minWidth: 0,
    paddingTop: 1,
  },
  listRowTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  listRowTitleWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
  },
  listRowTitle: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: SLACK_TYPE.listTitle,
    fontWeight: "500",
    color: SLACK_MOBILE.textPrimary,
    letterSpacing: -0.02,
  },
  listRowTitleMeta: {
    flexShrink: 0,
    fontSize: 11,
    fontWeight: "500",
    color: SLACK_MOBILE.textTertiary,
  },
  listRowTime: {
    fontSize: SLACK_TYPE.listTime,
    color: SLACK_MOBILE.textTertiary,
    fontWeight: "400",
    flexShrink: 0,
    paddingTop: 1,
    textTransform: "lowercase",
  },
  partyRecommendedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
    backgroundColor: "rgba(91, 94, 244, 0.06)",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_MOBILE.listDivider,
  },
  partyRecommendedHeaderTitle: {
    flex: 1,
    fontSize: 10,
    fontWeight: "700",
    color: PULSE_CHAT.accent,
    letterSpacing: 0.35,
    textTransform: "uppercase",
  },
  partyRecommendedHeaderMeta: {
    fontSize: 10,
    fontWeight: "600",
    color: SLACK_MOBILE.textSecondary,
  },
  partyRecommendedDivider: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_MOBILE.listDivider,
    backgroundColor: "#FAFAFA",
  },
  partyRecommendedDividerText: {
    fontSize: 9,
    fontWeight: "700",
    color: SLACK_MOBILE.textTertiary,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  listRowRecommended: {
    backgroundColor: "rgba(91, 94, 244, 0.03)",
  },
  listRowPartyLine: {
    fontSize: 9,
    fontWeight: "600",
    color: SLACK_MOBILE.textTertiary,
    letterSpacing: 0.4,
    marginTop: 1,
  },
  listRowPreview: {
    fontSize: SLACK_TYPE.listPreview,
    color: SLACK_MOBILE.textSecondary,
    lineHeight: 16,
    fontWeight: "400",
    marginTop: 2,
  },
  listRowPreviewStarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  listRowPreviewStarText: {
    flex: 1,
    minWidth: 0,
  },
  listRowPreviewStarBtn: {
    width: 36,
    height: 36,
    marginTop: -2,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  listRowPreviewStarBtnPressed: {
    opacity: 0.7,
  },
  listRowPreviewBelowMedia: {
    marginTop: 4,
    lineHeight: 17,
  },
  listRowSystemPreviewWrap: {
    marginTop: 2,
    gap: 3,
  },
  listRowPreviewBadge: {
    alignSelf: "flex-start",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.45,
    textTransform: "uppercase",
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
  },
  listRowPreviewBadgeSystem: {
    backgroundColor: PULSE_CHAT.accentSoft,
    borderColor: "rgba(91, 94, 244, 0.28)",
  },
  listRowPreviewBadgeTextSystem: {
    color: PULSE_CHAT.accent,
  },
  listRowPreviewBadgeImage: {
    backgroundColor: "rgba(14, 116, 144, 0.12)",
    borderColor: "rgba(14, 116, 144, 0.28)",
  },
  listRowPreviewBadgeTextImage: {
    color: "#0E7490",
  },
  listRowPreviewBadgeDocument: {
    backgroundColor: "rgba(180, 83, 9, 0.12)",
    borderColor: "rgba(180, 83, 9, 0.28)",
  },
  listRowPreviewBadgeTextDocument: {
    color: "#B45309",
  },
  threadHeader: {
    backgroundColor: "#FFFFFF",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_MOBILE.listDivider,
    paddingBottom: 12,
    gap: 8,
    zIndex: 20,
    ...Platform.select({
      ios: {
        shadowColor: "#181C32",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  threadHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    minHeight: 44,
  },
  threadBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(24, 28, 50, 0.09)",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    flexShrink: 0,
  },
  threadCenterPill: {
    flex: 1,
    flexDirection: "column",
    alignItems: "stretch",
    gap: 7,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(24, 28, 50, 0.08)",
    backgroundColor: "#FAFAFB",
    shadowColor: PULSE_CHAT.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 1,
    position: "relative",
    overflow: "hidden",
  },
  threadCenterMainRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    minWidth: 0,
    flex: 1,
    paddingTop: 2,
  },
  threadCenterToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    minWidth: 0,
  },
  threadTopAvatarChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(24, 28, 50, 0.08)",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  threadCenterMirrorSheen: {
    position: "absolute",
    left: 8,
    right: 8,
    top: 2,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.78)",
  },
  threadCenterAccentDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: PULSE_CHAT.accent,
    borderWidth: 1.25,
    borderColor: "#FFFFFF",
  },
  threadCenterTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 0,
  },
  threadTitle: {
    fontSize: SLACK_TYPE.threadTitle,
    fontWeight: "600",
    color: SLACK_MOBILE.textPrimary,
    letterSpacing: -0.05,
  },
  threadSubtitle: {
    fontSize: SLACK_TYPE.threadSubtitle,
    color: SLACK_MOBILE.textTertiary,
    fontWeight: "400",
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 3,
    minWidth: 0,
  },
  threadTopPartyTabs: {
    marginTop: 0,
    alignSelf: "stretch",
    width: "100%",
    minWidth: 0,
  },
  threadCompactRoleTag: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(91, 94, 244, 0.28)",
    backgroundColor: "#F4F6FF",
  },
  threadCompactRoleTagActive: {
    borderColor: PULSE_CHAT.accent,
    backgroundColor: PULSE_CHAT.accentSoft,
  },
  threadCompactRoleTagText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
    color: PULSE_CHAT.accent,
  },
  threadCompactRoleTagTextActive: {
    color: PULSE_CHAT.matteBlack,
  },
  threadMsgsContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 0,
  },
  threadMsgRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  threadMsgRowLead: {
    paddingTop: 11,
    paddingBottom: 5,
  },
  threadMsgRowPartyBreak: {
    marginTop: 8,
  },
  threadMsgRowContinuation: {
    paddingTop: 3,
    paddingBottom: 2,
  },
  threadMsgAvatarSpacer: {
    width: SLACK_AVATAR.thread,
    flexShrink: 0,
  },
  threadMsgAvatarCircle: {
    width: SLACK_AVATAR.thread,
    height: SLACK_AVATAR.thread,
    borderRadius: SLACK_AVATAR.thread / 2,
    overflow: "hidden",
    flexShrink: 0,
  },
  threadMsgBody: {
    flex: 1,
    minWidth: 0,
  },
  threadMsgHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 2,
  },
  threadMsgName: {
    fontSize: SLACK_TYPE.msgName,
    fontWeight: "600",
    color: SLACK_MOBILE.textPrimary,
    flexShrink: 1,
    letterSpacing: -0.1,
  },
  threadMsgTime: {
    fontSize: SLACK_TYPE.msgTime,
    fontWeight: "400",
    color: SLACK_MOBILE.textTertiary,
    flexShrink: 0,
  },
  threadMsgText: {
    fontSize: SLACK_TYPE.msgBody,
    fontWeight: "400",
    color: "#475569",
    lineHeight: 21,
  },
  threadMsgTextContinuation: {
    lineHeight: 21,
  },
  threadMsgTextStacked: {
    marginTop: 1,
  },
  waMsgOuterOwn: {
    width: "100%",
    alignItems: "flex-end",
    paddingTop: 3,
    paddingBottom: 3,
  },
  waMsgOuterOwnLead: {
    paddingTop: 10,
    paddingBottom: 4,
  },
  waMsgOuterOwnContinuation: {
    paddingTop: 2,
    paddingBottom: 2,
  },
  waMsgOuterOther: {
    width: "100%",
    alignItems: "flex-start",
  },
  waBubbleColumn: {
    maxWidth: "82%",
    minWidth: 0,
  },
  waBubbleOwn: {
    backgroundColor: CHAT_ACCENT,
    borderRadius: 12,
    borderBottomRightRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  waBubbleOther: {
    backgroundColor: CHAT_INCOMING_BUBBLE,
    borderRadius: 12,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: "flex-start",
  },
  waBubbleTextOwn: {
    fontSize: SLACK_TYPE.msgBody,
    fontWeight: "500",
    color: "#FFFFFF",
    lineHeight: 21,
  },
  waBubbleTextOther: {
    fontSize: SLACK_TYPE.msgBody,
    fontWeight: "500",
    color: CHAT_TEXT_PRIMARY,
    lineHeight: 21,
  },
  waMetaOwn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
    marginTop: 3,
    paddingHorizontal: 2,
  },
  waMetaOwnText: {
    fontSize: 10,
    fontWeight: "500",
    color: SLACK_MOBILE.textTertiary,
  },
  threadSysMsg: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  threadSysMsgText: {
    fontSize: SLACK_TYPE.msgBody,
    fontWeight: "400",
    color: SLACK_MOBILE.textSecondary,
    lineHeight: 20,
  },
  threadExpiryNotice: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
    alignItems: "center",
  },
  threadExpiryNoticeText: {
    fontSize: SLACK_TYPE.msgTime,
    fontWeight: "400",
    color: SLACK_MOBILE.textTertiary,
    lineHeight: 15,
    textAlign: "center",
    maxWidth: 300,
  },
  threadActions: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(24, 28, 50, 0.1)",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 2,
    paddingVertical: 2,
    shadowColor: PULSE_CHAT.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 1,
  },
  threadActionBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  threadPartyTabs: {
    paddingHorizontal: 8,
    paddingBottom: 2,
  },
  threadPartyTab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SLACK_MOBILE.chipBorder,
    backgroundColor: "#FFFFFF",
    maxWidth: 128,
    minHeight: 28,
    flexShrink: 0,
  },
  threadPartyTabOn: {
    borderColor: PULSE_CHAT.accent,
    backgroundColor: PULSE_CHAT.accentSoft,
  },
  threadPartyTabOff: {
    opacity: 0.55,
  },
  threadPartyTabName: {
    fontSize: 11,
    fontWeight: "500",
    color: SLACK_MOBILE.textPrimary,
  },
  threadPartyTabNameOn: {
    fontWeight: "600",
  },
  threadPartyTabRole: {
    fontSize: 10,
    fontWeight: "400",
    color: SLACK_MOBILE.textTertiary,
  },
  threadPartyTabRoleOn: {
    color: SLACK_MOBILE.textSecondary,
  },
  inboxToolbarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
  },
  inboxToolbarFilter: {
    flexShrink: 0,
  },
  inboxToolbarFilterInline: {
    flexShrink: 0,
    minHeight: 38,
    justifyContent: "center",
  },
  inboxToolbarFilterStandalone: {
    marginTop: 6,
    marginBottom: 0,
  },
  inboxToolbarSearch: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  searchToolbar: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 10,
  },
  searchToolbarInline: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  tripSearchStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: SLACK_MOBILE.searchBg,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  tripSearchStripInline: {
    flex: 1,
    minWidth: 0,
    minHeight: 38,
  },
  tripSearchInput: {
    flex: 1,
    fontSize: SLACK_TYPE.searchInput,
    color: SLACK_MOBILE.textPrimary,
    padding: 0,
    minWidth: 0,
    lineHeight: 17,
  },
  }),
);
