#!/usr/bin/env bash
# Rebuild the self-contained, rolled-back test scripts from _fixtures.sql + *.body.sql.
set -euo pipefail
cd "$(dirname "$0")"
for name in 02_security_tests 03_lifecycle; do
  {
    echo "-- GENERATED by build.sh from _fixtures.sql + ${name}.body.sql — edit those, not this file."
    echo "-- Single transaction; ends in ROLLBACK. Nothing persists. PREPROD only (run via run.sh)."
    echo "begin;"
    echo "set local statement_timeout = '60s';"
    echo "set local lock_timeout = '5s';"
    cat _fixtures.sql
    echo
    cat "${name}.body.sql"
  } > "${name}.sql"
  # Safety: exactly one transaction terminator, and it must be ROLLBACK.
  [ "$(grep -ciE '^(commit|end)[[:space:]]*;' "${name}.sql")" = "0" ] || { echo "ABORT: ${name}.sql contains COMMIT/END" >&2; exit 1; }
  [ "$(grep -ciE '^\s*rollback\s*;' "${name}.sql")" = "1" ] || { echo "ABORT: ${name}.sql must end with exactly one ROLLBACK" >&2; exit 1; }
  echo "built ${name}.sql"
done
