import Theme from "@pulse/core/constants/Theme";
import { Platform, StyleSheet } from "react-native";

/** Shared content rail — header / body / footer share this width + padding. */
export const CREATE_TRIP_DESKTOP_RAIL = {
  maxWidth: 1680,
  paddingHorizontal: 32,
} as const;

/** Touch target floor (Apple HIG / Android) — literal to avoid runtime Layout import issues in StyleSheet. */
const TOUCH = 44;

/** Desktop create-trip overlay — solid surfaces, aligned workspace rail. */
export const createTripDesktopStyles = StyleSheet.create({
  root: {
    flex: 1,
    width: "100%",
    backgroundColor: Theme.surface,
    overflow: "hidden",
  },
  rail: {
    width: "100%",
    maxWidth: CREATE_TRIP_DESKTOP_RAIL.maxWidth,
    alignSelf: "center",
    paddingHorizontal: CREATE_TRIP_DESKTOP_RAIL.paddingHorizontal,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    zIndex: 20,
    flexShrink: 0,
  },
  headerInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    minHeight: 56,
    position: "relative",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 96,
    zIndex: 2,
  },
  headerCenter: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 1,
  },
  headerRight: {
    minWidth: 96,
    alignItems: "flex-end",
    zIndex: 2,
  },
  closeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  closeBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.3,
  },
  headerStepBadge: {
    fontSize: 10,
    fontWeight: "600",
    color: Theme.textRouteCard,
    backgroundColor: Theme.surface,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
  },
  content: {
    flex: 1,
    backgroundColor: Theme.surface,
  },
  contentInner: {
    width: "100%",
    maxWidth: CREATE_TRIP_DESKTOP_RAIL.maxWidth,
    alignSelf: "center",
    paddingTop: 12,
    paddingHorizontal: CREATE_TRIP_DESKTOP_RAIL.paddingHorizontal,
    paddingBottom: 12,
  },
  stepSurface: {
    width: "100%",
    backgroundColor: Theme.cardWhite,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
    ...Platform.select({
      web: {
        boxShadow: "0 1px 3px rgba(15, 23, 42, 0.06)",
      },
      default: {},
    }),
  },
  stepSurfaceFill: {
    flex: 1,
    minHeight: 0,
  },
  stepSurfaceHeader: {
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 18,
    backgroundColor: Theme.cardWhite,
    gap: 16,
    maxWidth: 768,
    width: "100%",
    alignSelf: "center",
  },
  stepSurfaceDivider: {
    height: 1,
    backgroundColor: Theme.surfaceBorder,
    marginHorizontal: 28,
  },
  stepSurfaceBody: {
    paddingHorizontal: 28,
    paddingTop: 36,
    paddingBottom: 24,
    gap: 0,
    backgroundColor: Theme.cardWhite,
    alignItems: "stretch",
    width: "100%",
  },
  stepSurfaceBodyFill: {
    flex: 1,
    minHeight: 0,
    paddingVertical: 12,
  },
  stepSurfaceBodyKeypad: {
    paddingHorizontal: 0,
    paddingTop: 8,
    paddingBottom: 0,
    overflow: "hidden",
  },
  stepSurfaceBodyScroll: {
    flex: 1,
    minHeight: 0,
    width: "100%",
  },
  stepSurfaceBodyScrollContent: {
    paddingHorizontal: 28,
    paddingTop: 36,
    paddingBottom: 24,
    flexGrow: 1,
  },
  stepSubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textRouteCard,
    lineHeight: 16,
    textAlign: "center",
    alignSelf: "center",
    maxWidth: 560,
    width: "100%",
    marginTop: 2,
  },
  wizardWorkspace: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  /** Route step — full-width form (illustration sits under route tip). */
  wizardWorkspaceSolo: {
    width: "100%",
    alignSelf: "stretch",
  },
  wizardWorkspaceSoloFill: {
    width: "100%",
    alignSelf: "stretch",
    flex: 1,
    minHeight: 0,
  },
  wizardWorkspaceFill: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 24,
      width: "100%",
      flex: 1,
      minHeight: 0,
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
      flex: 1,
      minHeight: 0,
    },
  }),
  wizardWorkspaceMain: Platform.select({
    web: {
      flex: 0.72,
      minWidth: 0,
      gap: 0,
    } as const,
    default: {
      width: "100%",
    },
  }),
  wizardWorkspaceMainSolo: {
    width: "100%",
    maxWidth: 960,
    alignSelf: "center",
  },
  wizardWorkspaceMainMobile: {
    maxWidth: "100%",
    width: "100%",
    alignSelf: "stretch",
    paddingBottom: 8,
  },
  wizardWorkspaceMainMobileFill: {
    flex: 1,
    minHeight: 0,
    paddingBottom: 0,
  },
  /** Narrow / native — force single-column stacks (overrides web row Platform.select). */
  compactStack: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 16,
    width: "100%",
    alignSelf: "stretch",
  },
  compactStackTight: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    width: "100%",
    alignSelf: "stretch",
  },
  compactCol: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    gap: 10,
  },
  compactSourceModeCard: {
    minWidth: "100%",
    flexBasis: "100%",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 12,
    minHeight: TOUCH,
  },
  compactSourceModeIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
  },
  compactSourceModeTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  compactSourceModeSub: {
    fontSize: 11,
    lineHeight: 15,
  },
  compactSourceGuidanceBanner: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 4,
  },
  compactSourceGuidanceTitle: {
    fontSize: 10,
  },
  compactSourceGuidanceText: {
    fontSize: 12,
    lineHeight: 16,
  },
  compactEntityGridItem: {
    width: "100%",
    minWidth: 0,
  },
  compactDesktopClientGrid: {
    gap: 8,
  },
  compactDesktopEntityCard: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    gap: 10,
    minHeight: TOUCH,
  },
  compactDesktopEntityCardLeft: {
    gap: 10,
  },
  compactDesktopEntityTitle: {
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 17,
  },
  compactDesktopEntitySubtitle: {
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 15,
  },
  compactAllocationStepBody: {
    flex: 0,
    width: "100%",
    gap: 14,
  },
  compactAllocToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    width: "100%",
  },
  compactAssignLaterBox: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 180,
  },
  /** Mobile: partner name chip inline with Assign later. */
  allocPartnerNameChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    flexShrink: 1,
    maxWidth: "42%",
  },
  allocPartnerNameChipLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  allocPartnerNameChipValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    flexShrink: 1,
  },
  compactHeaderRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  /** Mobile party picker — label + add on one row, full-width search below. */
  compactPartyToolbar: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
    marginBottom: 4,
    width: "100%",
  },
  compactPartyToolbarTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
    minHeight: TOUCH,
  },
  compactPartySearchFull: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    maxWidth: "100%",
    minWidth: 0,
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    minHeight: TOUCH,
  },
  compactSectionHeading: {
    fontSize: 10,
    letterSpacing: 0.5,
    marginBottom: 0,
    lineHeight: 14,
  },
  compactAddClientBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: TOUCH,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  compactAddClientBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  compactStepBody: {
    gap: 10,
  },
  compactStepSection: {
    gap: 6,
  },
  /** Mobile route — single column, no flex:1 children inside ScrollView. */
  compactRouteBody: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
  },
  compactRouteFieldsStack: {
    position: "relative",
    gap: 8,
    width: "100%",
  },
  compactRouteSwapRow: {
    justifyContent: "center",
    paddingRight: 0,
    marginTop: -2,
    marginBottom: -2,
    zIndex: 1,
  },
  compactQuickDateRow: {
    width: "100%",
    flexWrap: "nowrap",
    gap: 6,
  },
  compactQuickDateChip: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minHeight: 36,
  },
  compactRouteDateInputShell: {
    minHeight: 40,
    paddingVertical: 8,
  },
  wizardWorkspaceMainFill: Platform.select({
    web: {
      flex: 0.72,
      minWidth: 0,
      minHeight: 0,
      flexDirection: "column",
    } as const,
    default: {
      width: "100%",
      flex: 1,
      minHeight: 0,
    },
  }),
  wizardWorkspaceAside: Platform.select({
    web: {
      flex: 0.28,
      minWidth: 240,
      maxWidth: 340,
    } as const,
    default: {
      width: "100%",
    },
  }),
  routeStepGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 28,
      width: "100%",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  /** Contract lane: date is primary; corridor summary is secondary. */
  routeStepGridContract: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 28,
      width: "100%",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  routeStepCol: {
    flex: 1,
    minWidth: 0,
    gap: 12,
  },
  routeStepColPrimary: {
    flex: 1.35,
    minWidth: 0,
    gap: 12,
  },
  routeStepColSecondary: {
    flex: 0.9,
    minWidth: 0,
    gap: 12,
  },
  routeDateSectionHero: {
    gap: 10,
  },
  routeDateHeroHint: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 17,
    marginBottom: 2,
  },
  quickDateRowHero: {
    gap: 10,
  },
  quickDateChipHero: {
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 14,
  },
  quickDateChipTextHero: {
    fontSize: 13,
    fontWeight: "700",
  },
  routeDateInputShellHero: {
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 4,
  },
  dateInputHero: {
    fontSize: 16,
    fontWeight: "700",
  },
  routeDateNativeValueHero: {
    fontSize: 16,
    fontWeight: "700",
  },
  routeContractSummary: {
    gap: 10,
  },
  routeContractHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 28,
  },
  routeContractHeaderTitle: {
    flex: 1,
    minWidth: 0,
  },
  routeChangeLaneBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    backgroundColor: Theme.cardWhite,
    minHeight: 32,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  routeChangeLaneBtnCompact: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    minHeight: 30,
    borderRadius: 7,
    gap: 4,
  },
  routeChangeLaneBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.primary,
  },
  routeChangeLaneBtnTextCompact: {
    fontSize: 10,
  },
  routeContractCard: {
    borderWidth: 1,
    borderColor: Theme.borderInput,
    backgroundColor: Theme.surfaceGray,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  routeContractNode: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  routeContractPin: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    alignItems: "center",
    justifyContent: "center",
  },
  routeContractPinDrop: {
    backgroundColor: Theme.fiscalTabActiveBg,
  },
  routeContractNodeCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  routeContractNodeLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  routeContractNodeValue: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  routeContractDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 8,
  },
  routeContractRule: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderMedium,
  },
  routeContractLockedHint: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 15,
  },
  routeDateInputShell: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
  },
  routeDateNativeValue: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
  stepBody: {
    width: "100%",
    alignSelf: "stretch",
    gap: 16,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    zIndex: 30,
    flexShrink: 0,
  },
  footerInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 8,
    gap: 12,
  },
  footerBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 7,
    paddingHorizontal: 12,
    minWidth: 80,
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  footerBackBtnHidden: {
    opacity: 0,
    pointerEvents: "none",
  },
  footerBackBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  footerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
  },
  footerInlineHint: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    maxWidth: 220,
    textAlign: "right",
  },
  footerPrimaryWrap: {
    flexShrink: 0,
  },
  /** Same chrome as OperationalButton / mobile FullPageWizardFooter — all steps. */
  footerPrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 22,
    borderRadius: 12,
    backgroundColor: Theme.accentBrown,
    minHeight: 36,
    minWidth: 128,
    borderWidth: 1,
    borderColor: Theme.accentBrownDeep,
    ...Platform.select({
      web: {
        cursor: "pointer" as const,
        boxShadow: "0 1px 4px rgba(77, 54, 54, 0.16)",
      },
      default: {},
    }),
  },
  footerPrimaryBtnDisabled: {
    backgroundColor: Theme.surfaceGray,
    borderColor: Theme.borderInput,
  },
  footerPrimaryBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textOnPrimary,
  },
  footerPrimaryBtnTextDisabled: {
    color: Theme.textMuted,
  },
  footerSpacer: {
    width: 80,
  },
  footerHint: {
    marginTop: 4,
    textAlign: "right",
    fontSize: 10,
    color: Theme.textMuted,
    fontWeight: "400",
  },
  stepperWrap: {
    width: "100%",
    position: "relative",
    paddingHorizontal: 4,
    maxWidth: 720,
    alignSelf: "center",
  },
  stepperTrack: {
    position: "absolute",
    left: "8%",
    right: "8%",
    top: 14,
    height: 1.5,
    backgroundColor: "rgba(226, 232, 240, 0.85)",
    borderRadius: 999,
    zIndex: 0,
    overflow: "hidden",
  },
  stepperTrackFill: {
    height: "100%",
    backgroundColor: Theme.positive,
    borderRadius: 999,
    ...Platform.select({
      web: {
        transitionProperty: "width",
        transitionDuration: "0.32s",
        transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
      } as object,
      default: {},
    }),
  },
  stepperRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    zIndex: 1,
    width: "100%",
  },
  stepperItemHit: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
  },
  stepperItem: {
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 2,
    minWidth: 0,
    width: "100%",
  },
  stepperCircleRing: {
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  stepperCircle: {
    width: 28,
    height: 28,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  stepperCircleActiveShadow: {
    ...Platform.select({
      web: { boxShadow: "0 1px 5px rgba(15, 23, 42, 0.16)" },
      default: {
        shadowColor: Theme.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.14,
        shadowRadius: 3,
        elevation: 2,
      },
    }),
  },
  stepperCircleActive: {
    backgroundColor: Theme.textPrimaryDark,
    borderColor: Theme.textPrimaryDark,
  },
  stepperCircleActiveRing: {
    padding: 3,
    borderRadius: 12,
    backgroundColor: Theme.surfaceBorder,
  },
  stepperCircleDoneRing: {
    padding: 3,
    borderRadius: 12,
    backgroundColor: Theme.positiveMuted,
  },
  stepperCircleDone: {
    backgroundColor: Theme.positive,
    borderColor: Theme.positive,
  },
  stepperCircleFuture: {
    backgroundColor: Theme.surfaceGray,
    borderColor: Theme.borderLight,
  },
  stepperCircleText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  stepperCircleTextActive: {
    color: Theme.textOnPrimary,
  },
  stepperCircleTextDone: {
    color: Theme.textOnPrimary,
  },
  stepperLabel: {
    fontSize: 8,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.35,
    color: Theme.textMuted,
    textAlign: "center",
    width: "100%",
  },
  stepperLabelActive: {
    color: Theme.accentBrown,
    fontWeight: "700",
  },
  stepperLabelDone: {
    color: Theme.positive,
    fontWeight: "700",
  },
  /** Step body fade-in-up (HTML animate-fade-in-up). */
  stepFadeWrap: {
    width: "100%",
  },
  /** Main card scale-in entrance. */
  stepSurfaceAnimated: {
    width: "100%",
  },
  /** Shared two-column step layout — fills the step surface width. */
  stepTwoColGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  stepTwoColMain: Platform.select({
    web: {
      flex: 1,
      minWidth: 0,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  stepTwoColAside: Platform.select({
    web: {
      flex: 1,
      minWidth: 0,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  stepTwoColMainNarrow: Platform.select({
    web: {
      flex: 0.42,
      minWidth: 300,
      maxWidth: 440,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  stepTwoColAsideWide: Platform.select({
    web: {
      flex: 0.58,
      minWidth: 0,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  stepSection: {
    width: "100%",
    alignSelf: "stretch",
    gap: 10,
  },
  stepGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  stepGridMain: {
    flex: 1,
    minWidth: 0,
    gap: 12,
  },
  stepGridAside: Platform.select({
    web: {
      flex: 1,
      minWidth: 0,
      gap: 12,
      justifyContent: "flex-start",
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  /** Commodity & client — narrow load fields + wide client picker. */
  commodityClientGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  commodityClientLoadCol: Platform.select({
    web: {
      flex: 0.42,
      minWidth: 260,
      maxWidth: 420,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  commodityClientPickerCol: Platform.select({
    web: {
      flex: 0.58,
      minWidth: 0,
      gap: 12,
    } as const,
    default: {
      width: "100%",
      gap: 12,
    },
  }),
  commodityClientSection: {
    width: "100%",
    alignSelf: "stretch",
    gap: 10,
  },
  summaryCardFull: {
    width: "100%",
    alignSelf: "stretch",
  },
  allocationColumns: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 24,
      width: "100%",
      flex: 1,
      minHeight: 0,
      alignSelf: "stretch",
    } as const,
    default: {
      gap: 20,
      width: "100%",
    },
  }),
  allocationColumn: {
    flex: 1,
    minWidth: 0,
    gap: 10,
    minHeight: 0,
  },
  allocationStepBody: {
    width: "100%",
    flex: 1,
    minHeight: 0,
    gap: 16,
  },
  allocationToolbar: {
    width: "100%",
    gap: 12,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFleetPanel: {
    width: "100%",
    flex: 1,
    minHeight: 0,
    gap: 12,
  },
  allocationWarnCompact: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: Theme.warningMuted,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  allocationWarnCompactText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "500",
    color: Theme.warning,
    lineHeight: 14,
  },
  fieldSection: {
    width: "100%",
    gap: 10,
    flexGrow: 0,
    flexShrink: 0,
  },
  /** Single allocation form — equal columns, no flex-overlap on stacks. */
  allocationForm: {
    width: "100%",
    gap: 16,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFormRow: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 16,
      width: "100%",
    },
  }),
  allocationFormRowTop: {
    alignItems: "flex-start",
  },
  /** Phone + lookup alert side-by-side; alert aligns with the input shell. */
  allocationPhoneAlertRow: {
    alignItems: "flex-start",
  },
  allocationPhoneAlertCol: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  allocationPhoneAlertSpacer: {
    opacity: 0,
  },
  allocationFormCol: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  allocationFieldBlock: {
    width: "100%",
    gap: 8,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFieldBlockFull: {
    width: "100%",
    gap: 8,
    flexGrow: 0,
    flexShrink: 0,
    marginTop: 0,
  },
  sectionHeading: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    color: Theme.textMuted,
    marginBottom: 6,
  },
  routeGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 20,
      width: "100%",
      alignSelf: "stretch",
    } as const,
    default: {
      flexDirection: "column",
      gap: 16,
      width: "100%",
    },
  }),
  routeGridMain: {
    flex: 1,
    minWidth: 0,
    gap: 14,
  },
  routeGridAside: Platform.select({
    web: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    } as const,
    default: {
      width: "100%",
      gap: 14,
    },
  }),
  routeFieldsStack: {
    gap: 8,
    position: "relative",
  },
  pickupRecommendBlock: {
    gap: 10,
    width: "100%",
    marginBottom: 6,
  },
  pickupRecommendBlockCompact: {
    gap: 6,
    marginBottom: 2,
  },
  pickupRecommendLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  pickupRecommendRow: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 8,
    alignItems: "stretch",
  },
  pickupRecommendChip: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    maxWidth: 240,
    minWidth: 168,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    minHeight: 64,
  },
  pickupRecommendChipActive: {
    borderColor: Theme.textPrimaryDark,
    backgroundColor: Theme.textPrimaryDark,
  },
  pickupRecommendChipCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pickupRecommendChipTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    lineHeight: 17,
  },
  pickupRecommendChipTitleActive: {
    color: Theme.textOnPrimary,
  },
  pickupRecommendChipSub: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 15,
  },
  pickupRecommendChipSubActive: {
    color: Theme.textOnPrimary,
    opacity: 0.85,
  },
  pickupRecommendHint: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 16,
    marginTop: -2,
  },
  pickupRecommendEmpty: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 17,
    flex: 1,
    minWidth: 0,
  },
  pickupLocEmptyBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
  },
  pickupLocSections: {
    gap: 16,
    width: "100%",
  },
  pickupLocSectionsCompact: {
    gap: 8,
  },
  pickupLocSection: {
    gap: 8,
    width: "100%",
  },
  pickupLocSectionHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pickupLocSectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.1,
  },
  pickupLocSectionCount: {
    marginLeft: 2,
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    backgroundColor: Theme.surfaceGray,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: "hidden",
  },
  pickupLocSectionEmpty: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 16,
    paddingVertical: 4,
  },
  pickupLocGrid: Platform.select({
    web: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      width: "100%",
    } as const,
    default: {
      gap: 8,
      width: "100%",
    },
  }),
  pickupLocGridCompact: {
    flexDirection: "column",
    flexWrap: "nowrap",
    gap: 8,
  },
  pickupLocGridItem: {
    flexGrow: 1,
    flexBasis: 260,
    minWidth: 220,
    maxWidth: "100%",
  },
  pickupLocGridItemCompact: {
    width: "100%",
    minWidth: 0,
    flexBasis: "auto",
    maxWidth: "100%",
  },
  pickupLocCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    minHeight: 88,
  },
  pickupLocCardCompact: {
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    minHeight: 56,
  },
  pickupLocCardSelected: {
    borderColor: Theme.textPrimaryDark,
    backgroundColor: Theme.surface,
  },
  pickupLocIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.surfaceGray,
    flexShrink: 0,
  },
  pickupLocIconWrapCompact: {
    width: 28,
    height: 28,
    borderRadius: 8,
  },
  pickupLocIconWrapSelected: {
    backgroundColor: Theme.textPrimaryDark,
  },
  pickupLocCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  pickupLocCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pickupLocTypePill: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.3,
    textTransform: "uppercase",
    flexShrink: 1,
  },
  pickupLocTypePillSelected: {
    color: Theme.textRouteCard,
  },
  pickupLocCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.textPrimaryDark,
    flexShrink: 0,
  },
  pickupLocCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    lineHeight: 18,
    letterSpacing: -0.15,
  },
  pickupLocCardTitleCompact: {
    fontSize: 13,
    lineHeight: 16,
  },
  pickupLocCardTitleSelected: {
    color: Theme.textPrimaryDark,
  },
  pickupLocCardAddress: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 16,
  },
  pickupLocCardAddressCompact: {
    fontSize: 11,
    lineHeight: 14,
  },
  pickupLocCardAddressSelected: {
    color: Theme.textSecondary,
  },
  routeConnector: {
    position: "absolute",
    left: 23,
    top: 44,
    bottom: 28,
    width: 2,
    borderLeftWidth: 2,
    borderStyle: "dashed",
    borderColor: Theme.borderLight,
    zIndex: 0,
  },
  routeFieldBlock: {
    gap: 8,
    zIndex: 1,
  },
  routeFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    color: Theme.textMuted,
    marginBottom: 6,
  },
  routeFieldLabelPickup: {
    color: Theme.textSecondary,
  },
  routeFieldLabelDrop: {
    color: Theme.textSecondary,
  },
  routeInputShell: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    minHeight: 42,
    ...Platform.select({
      web: {
        boxShadow: "0 1px 2px rgba(15, 23, 42, 0.04)",
      },
      default: {},
    }),
  },
  routeInputShellError: {
    borderColor: Theme.destructive,
  },
  routeInputFlex: {
    flex: 1,
    minWidth: 0,
  },
  routeDateSection: {
    gap: 10,
  },
  quickDateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickDateChip: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    minHeight: 36,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  quickDateChipActive: {
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
    ...Platform.select({
      web: { boxShadow: "0 1px 3px rgba(77, 54, 54, 0.12)" },
      default: {},
    }),
  },
  quickDateChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  quickDateChipTextActive: {
    color: Theme.textOnPrimary,
    fontWeight: "700",
  },
  routeSwapRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingRight: 10,
    marginTop: -2,
    marginBottom: -2,
    zIndex: 2,
  },
  routeSwapBtn: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      web: {
        cursor: "pointer" as const,
        boxShadow: "0 1px 2px rgba(15, 23, 42, 0.06)",
      },
      default: {},
    }),
  },
  dateInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 16,
    marginTop: 4,
  },
  routeInfoBannerBelowPickup: {
    marginTop: 12,
    width: "100%",
    alignSelf: "stretch",
  },
  infoBannerIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 1,
  },
  infoBannerIconInner: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  infoBannerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  infoBannerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoBannerTitle: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    color: Theme.textPrimaryDark,
  },
  infoBannerBody: {
    fontSize: 11,
    fontWeight: "400",
    color: Theme.textRouteCard,
    lineHeight: 16,
  },
  routeSummary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    overflow: "hidden",
  },
  routeSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  routeSummaryIcon: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  routeSummaryTitle: {
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    lineHeight: 19,
  },
  routeSummaryArrow: {
    color: Theme.textMuted,
    opacity: 0.85,
  },
  routeSummaryMetrics: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: Theme.cardWhite,
  },
  routeSummaryMetric: {
    flex: 1,
    paddingHorizontal: 8,
  },
  routeSummaryMetricBorder: {
    borderRightWidth: 1,
    borderRightColor: Theme.borderLight,
  },
  routeSummaryMetricLabel: {
    fontSize: 10,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: Theme.textMuted,
    marginBottom: 4,
  },
  routeSummaryMetricValue: {
    fontSize: 12,
    fontWeight: "500",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
  },
  nonRouteStepWrap: {
    width: "100%",
    alignSelf: "stretch",
    gap: 16,
  },
  formFieldInput: {
    width: "100%",
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    minHeight: 42,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  asideArtPanel: {
    width: "100%",
    backgroundColor: Theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    gap: 6,
    overflow: "hidden",
    alignItems: "center",
    ...Platform.select({
      web: {
        position: "sticky" as const,
        top: 88,
      },
      default: {},
    }),
  },
  asideArtGlow: {
    position: "absolute",
    top: -40,
    right: -30,
    width: 160,
    height: 160,
    borderRadius: 999,
    backgroundColor: Theme.positiveMuted,
    opacity: 0.45,
  },
  asideArtEyebrow: {
    alignSelf: "flex-start",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.55,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  asideArtTitle: {
    alignSelf: "flex-start",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: -0.2,
    color: Theme.textPrimaryDark,
    lineHeight: 18,
  },
  asideArtBody: {
    alignSelf: "flex-start",
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 16,
  },
  asideArtLottieWrap: {
    width: "100%",
    height: 180,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  asideArtLottie: {
    width: 200,
    height: 180,
  },
  asideArtPanelInline: {
    marginTop: 4,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 16,
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
    ...Platform.select({
      web: { position: "relative" as const, top: undefined },
      default: {},
    }),
  },
  asideArtLottieWrapInline: {
    height: 148,
    marginTop: 0,
  },
  asideArtLottieInline: {
    width: 180,
    height: 148,
  },
  allocDesktopToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Theme.surfaceBorder,
    marginBottom: 4,
  },
  /** Partner summary in the Assign-later toolbar row (aggregate). */
  allocToolbarPartnerCard: {
    flexGrow: 0,
    flexShrink: 1,
    minWidth: 160,
    maxWidth: 280,
  },
  allocToolbarPartnerCardInner: {
    width: "100%",
    alignSelf: "stretch",
  },
  sourceModeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    width: "100%",
  },
  sourceModeCard: {
    flex: 1,
    minWidth: 200,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  sourceModeCardActive: {
    borderColor: Theme.textPrimaryDark,
    borderWidth: 2,
    backgroundColor: Theme.cardWhite,
  },
  sourceModeIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  sourceModeIconActive: {
    backgroundColor: Theme.textPrimaryDark,
  },
  sourceModeCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  sourceModeTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  sourceModeTitleActive: {
    color: Theme.textPrimaryDark,
  },
  sourceModeSub: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 16,
  },
  sourceGuidanceBanner: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    gap: 4,
  },
  sourceGuidanceTitle: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: Theme.textPrimaryDark,
  },
  sourceGuidanceText: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    lineHeight: 18,
  },
  sourceAggregatePanel: {
    width: "100%",
    gap: 16,
  },
  sourceRatesBlock: {
    width: "100%",
    gap: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Theme.surfaceBorder,
  },
  sourceRateSummaryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  sourceRateSummaryCardError: {
    borderColor: Theme.destructive,
  },
  sourceRateSummaryCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  sourceRateSummaryLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  sourceRateSummaryValue: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
    color: Theme.textPrimaryDark,
  },
  sourceRateSummaryValueMuted: {
    fontSize: 15,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  sourceRateSummaryAdvance: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    marginTop: 2,
  },
  sourceRateSummaryAction: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
  },
  sourceRateSummaryActionText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textRouteCard,
  },
  sourceSummaryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  sourceSummaryChipLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  sourceSummaryChipValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  allocModeTabs: {
    flexDirection: "row",
    padding: 4,
    borderRadius: 16,
    backgroundColor: Theme.surface,
    gap: 4,
  },
  allocModeTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  allocModeTabActive: {
    backgroundColor: Theme.cardWhite,
    ...Platform.select({
      web: { boxShadow: "0 1px 2px rgba(15, 23, 42, 0.06)" },
      default: {},
    }),
  },
  allocModeTabText: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textRouteCard,
  },
  allocModeTabTextActive: {
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  allocAssignLaterBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    minWidth: 240,
  },
  allocAssignLaterCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  allocAssignLaterTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  allocAssignLaterSub: {
    fontSize: 10,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  allocAssignLaterHint: {
    fontSize: 10,
    fontWeight: "500",
    color: Theme.textMuted,
    marginBottom: 8,
  },
  allocAssignLaterBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: Theme.warningMuted,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    marginBottom: 8,
  },
  allocAssignLaterBannerText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "500",
    color: Theme.warning,
    lineHeight: 18,
  },
  allocAssignLaterBannerStrong: {
    fontWeight: "700",
  },
  allocationAggregatePanel: {
    width: "100%",
    gap: 20,
  },
  commodityClientHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
    flexWrap: "wrap",
  },
  commodityClientHeaderTitle: {
    flexShrink: 0,
  },
  desktopPartySearch: {
    flex: 1,
    minWidth: 140,
    maxWidth: 280,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
  },
  desktopPartySearchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textPrimaryDark,
    padding: 0,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
      default: {},
    }),
  },
  desktopPartySearchEmpty: {
    width: "100%",
    paddingVertical: 16,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  commodityAddClientBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  commodityAddClientBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  salePriceField: {
    gap: 8,
  },
  salePriceInputShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  salePriceCurrency: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  aggregateCurrency: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  aggregateAmountInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    padding: 0,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  desktopPlainInput: {
    width: "100%",
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  /** India mobile: flag + +91 | 10-digit local number */
  inPhoneFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    paddingLeft: 12,
    paddingRight: 10,
    paddingVertical: 2,
  },
  inPhoneCcBlock: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingRight: 10,
    marginRight: 10,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: Theme.borderLight,
  },
  inPhoneCcText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.2,
  },
  inPhoneDigitsInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    paddingVertical: 10,
    paddingHorizontal: 0,
    letterSpacing: 0.4,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  inPhoneDigitHint: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  salePriceInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    padding: 0,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  salePriceError: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.destructive,
  },
  inputBoxClean: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    ...Platform.select({
      web: {
        transitionProperty: "border-color, background-color, box-shadow",
        transitionDuration: "0.2s",
      },
      default: {},
    }),
  },
  inputBoxCleanError: {
    borderColor: Theme.destructive,
  },
  desktopFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    color: Theme.textMuted,
    marginBottom: 6,
  },
  desktopEntityCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: "rgba(248, 250, 252, 0.6)",
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  desktopEntityCardSelected: {
    borderColor: Theme.textPrimaryDark,
    backgroundColor: Theme.cardWhite,
    borderWidth: 2,
    ...Platform.select({
      web: { boxShadow: "0 1px 3px rgba(15, 23, 42, 0.08)" },
      default: {},
    }),
  },
  desktopEntityCardDisabled: {
    opacity: 0.5,
    backgroundColor: Theme.surfaceGray,
  },
  desktopEntityCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  desktopEntityAvatar: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  desktopEntityAvatarSquare: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  desktopEntityAvatarSelected: {
    backgroundColor: Theme.textPrimaryDark,
  },
  desktopEntityAvatarText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textRouteCard,
  },
  desktopEntityAvatarTextSelected: {
    color: Theme.textOnPrimary,
  },
  desktopEntityCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  desktopEntityTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  desktopEntitySubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  desktopStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  desktopStatusBadgeAvailable: {
    backgroundColor: Theme.positiveMuted,
  },
  desktopStatusBadgeBusy: {
    backgroundColor: Theme.warningMuted,
  },
  desktopStatusBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  desktopStatusBadgeTextAvailable: {
    color: Theme.positive,
  },
  desktopStatusBadgeTextBusy: {
    color: Theme.warning,
  },
  desktopPill: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  desktopPillFlex: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  desktopPillBlock: {
    width: "100%",
    alignSelf: "stretch",
  },
  desktopPillActive: {
    borderColor: Theme.textPrimaryDark,
    backgroundColor: Theme.textPrimaryDark,
    ...Platform.select({
      web: { boxShadow: "0 1px 3px rgba(15, 23, 42, 0.12)" },
      default: {},
    }),
  },
  desktopPillText: {
    fontSize: 10,
    fontWeight: "600",
    color: Theme.textRouteCard,
    textAlign: "center",
  },
  desktopPillTextActive: {
    fontWeight: "700",
    color: Theme.textOnPrimary,
  },
  desktopCountBadge: {
    backgroundColor: Theme.surface,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  desktopCountBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textRouteCard,
  },
  desktopPickerStack: {
    gap: 8,
    width: "100%",
  },
  desktopSelectionSummaryWrap: {
    width: "100%",
  },
  desktopPickerHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  desktopChangeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  desktopChangeBtnText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.primary,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  desktopChangePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
  },
  desktopChangePillText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  desktopScrollList: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  desktopScrollListContent: {
    paddingRight: 4,
  },
  /**
   * Compact (phone/tablet) entity list — full-width rows, not wrapped tiles.
   * Row-wrap here let cards shrink to content, clipping driver/vehicle names
   * down to just the avatar + status badge on iPad.
   */
  desktopEntityGridFlow: {
    width: "100%",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
  },
  desktopClientGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    width: "100%",
  },
  desktopClientGridItem: {
    width: "48%",
    minWidth: 0,
  },
  desktopListSection: {
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  desktopListSectionHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  desktopListSectionHeadRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  desktopListAddBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      web: {
        cursor: "pointer" as const,
        boxShadow: "0 1px 2px rgba(15, 23, 42, 0.06)",
      },
      default: {},
    }),
  },
  desktopInlineErrorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  desktopInlineErrorText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.destructive,
  },
  desktopLocationShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    minHeight: 56,
  },
  desktopLocationIconBox: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  desktopLocationValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  desktopLocationValueFilled: {
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  saleClientCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
  },
  saleClientCopy: {
    flex: 1,
    minWidth: 0,
  },
  saleClientAvatar: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: Theme.textPrimaryDark,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  saleClientAvatarText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnPrimary,
  },
  saleClientName: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  saleClientPhone: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textMuted,
    marginTop: 2,
  },
  saleClientMissing: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textMuted,
    paddingVertical: 8,
  },
  saleTermsGap: {
    marginTop: 8,
  },
  compactSaleTermsGap: {
    marginTop: 12,
  },
  compactSaleInfoBanner: {
    marginTop: 4,
  },
  paymentTermsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
  },
  /** Mobile sale — Google/pay full-page keypad host. */
  saleMobileKeypadRoot: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignSelf: "stretch",
    gap: 8,
  },
  lanePathBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    backgroundColor: Theme.surfaceGray,
  },
  lanePathBannerText: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  lanePathBannerAction: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.primary,
  },
  saleMobileTermsBlock: {
    width: "100%",
    gap: 6,
  },
  /** Mobile: three equal chips in one horizontal row. */
  saleMobilePaymentTermsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "stretch",
    gap: 6,
    width: "100%",
  },
  sourceChangePartnerLink: {
    alignSelf: "center",
    paddingVertical: 8,
    minHeight: 40,
    justifyContent: "center",
    flexShrink: 0,
  },
  sourceChangePartnerLinkText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  sourcePartnerRateKeypadPage: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignSelf: "stretch",
  },
});
