import { PULSE_SIGNUP_TYPO } from './signUpTypography';

/** Shared sizing for business + driver mobile signup — aligned with PULSE_SIGNUP_TYPO. */
export const SIGNUP_MOBILE_TOKENS = {
  padH: 20,
  contentMaxWidth: 360,
  brandSize: PULSE_SIGNUP_TYPO.brand.fontSize,
  backFontSize: PULSE_SIGNUP_TYPO.back.fontSize,
  titleSize: PULSE_SIGNUP_TYPO.title.fontSize,
  titleLineHeight: PULSE_SIGNUP_TYPO.title.lineHeight,
  subtitleSize: PULSE_SIGNUP_TYPO.subtitle.fontSize,
  subtitleLineHeight: PULSE_SIGNUP_TYPO.subtitle.lineHeight,
  fieldLabelSize: PULSE_SIGNUP_TYPO.label.fontSize,
  fieldLabelSpacing: PULSE_SIGNUP_TYPO.label.letterSpacing,
  displayFontSize: PULSE_SIGNUP_TYPO.display.fontSize,
  displayMinHeight: 48,
  inputFontSize: PULSE_SIGNUP_TYPO.input.fontSize,
  inputMinHeight: 48,
  btnFontSize: 12,
  btnPaddingV: 10,
  btnRadius: 12,
  inputRadius: 12,
  googleBtnPaddingV: 11,
  orMarginV: 10,
  altMarginTop: 14,
  altFontSize: PULSE_SIGNUP_TYPO.linkSmall.fontSize,
  linkFontSize: PULSE_SIGNUP_TYPO.linkSmall.fontSize,
  heroPadBottom: 12,
  displayBlockMarginBottom: 4,
  progressPadTop: 10,
  progressLabelSize: PULSE_SIGNUP_TYPO.progressLabel.fontSize,
  otpBoxW: 36,
  otpBoxH: 42,
  otpGap: 7,
  otpDigitSize: PULSE_SIGNUP_TYPO.otpDigit.fontSize,
  flagSize: 18,
  dialCodeSize: PULSE_SIGNUP_TYPO.displayPrefix.fontSize,
} as const;
